import PySimpleGUI as sg
from generate_allproc_boilerplate import selectcomponents

def gui_layer_generation(path, G4_Data, topas_application_path):
  general_layer = sg.Frame('General Settings',
                  [ 
                    [sg.Text('Main Folder',size =(17,1),font=('Helvetica', 14),text_color='black'),
                      sg.In(default_text=path,key='-MAINFOLDERNAME-',size=(50,1),font=('Helvetica', 14),enable_events=True),sg.FolderBrowse(font=('Helvetica', 14))],
                    [sg.Text('G4 Data Directory',size = (17,1),font=('Helvetica', 14), text_color='black'),
                      sg.In(default_text=G4_Data,key='-G4FOLDERNAME-',size=(50,1),font=('Helvetica', 14),enable_events=True, tooltip="Click the enter key to register the change"),sg.FolderBrowse(font=('Helvetica', 14))],
                    [sg.Text('TOPAS Directory',size =(17,1),font=('Helvetica', 14),text_color='black'),
                      sg.In(default_text=topas_application_path,key='-TOPAS-',size=(50,1),font=('Helvetica', 14),enable_events=True, tooltip="Click the enter key to register the change"),sg.FileBrowse(font=('Helvetica', 14))],
                    [sg.Text('Seed',size =(9,1),font=('Helvetica', 14),text_color='black'),
                      sg.In(default_text='9',key='-SEED-',size=(10,1),font=('Helvetica', 14),enable_events=True)],
                    [sg.Text('Threads',size = (9,1),font=('Helvetica', 14),text_color='black'),
                      sg.In(default_text='4',key='-THREAD-',size=(10,1),font=('Helvetica',14),enable_events=True)],
                    [sg.Text('Histories',size = (9,1),font=('Helvetica',14),text_color='black'),
                      sg.In(default_text='100000',key='-HIST-',size=(10,1),font=('Helvetica',14),enable_events=True)],
                ])
  return general_layer

information_layer = sg.Frame('Instructions on the usage of the GUI', 
                             [ 
                               [sg.Text('Select your Topas and G4 data directories, remember to press the enter key to update the selection ')],
                               [sg.Text('Select the function you would like to enable: ')],
                               [sg.Text('   DICOM allows the user to specify a DICOM image folder to run simulations on')],
                               [sg.Text('   Optimisation generation for running simulations and batch testing')],
                               [sg.Text('In the following pages, type in your desired value and press the enter key. ')],
                               [sg.Text('By default all lengths are in units of cm and all angles are in units of degrees.')],
                               
                             ]) 

runbuttons_layer= sg.Frame('Activate simulation', 
                           [
                             [sg.Button("Generate Processes", enable_events=True, key='-GEN-', disabled=False, font=('Helvetica', 14), disabled_button_color='grey'),
                              sg.Button("Run", enable_events=True, key='-RUN-', disabled=False, font=('Helvetica', 14), disabled_button_color='grey'),
                              sg.Button("Generate process and run", enable_events=True, key='-GENRUN-', disabled=False)],
                            ], key ='-BUTTONSACTIVATE-', 
                              visible = False)

function_layer = sg.Frame('Choose your function',
                          [
                            [sg.Checkbox('Use DICOM', enable_events=True, key='-DICOMACTIVATECHECK-'),
                             sg.Checkbox('Optimisation generation', enable_events=True , key='-USERACTIVATECHECK-')
                             ],
                          ])

dicom_layer = sg.pin(sg.Frame("DICOM inputs",
                              [ 
                                [sg.Text('DICOM Directory',size =(17,1),font=('Helvetica', 14),text_color='black'),
                                 sg.In(default_text='dicom_path',key='-DICOM-',size=(50,1),font=('Helvetica', 14),enable_events=True,
                                       tooltip="Click the enter key to register the change"),sg.FolderBrowse(font=('Helvetica', 14))
                                ],
                                [sg.Text('DICOM RP file',size =(17,1),font=('Helvetica', 14),text_color='black'),
                                 sg.In(default_text='dicom_RP_path',key='-DICOMRP-',size=(50,1),font=('Helvetica', 14),enable_events=True,
                                       tooltip="Click the enter key to register the change"),sg.FileBrowse(font=('Helvetica', 14))
                                ],
                                [sg.Button("Create new DICOM bat file and run",enable_events=True, key='-DICOMBAT-',font=('Helvetica', 14),size=(35,1))],
                              ],
                              key ='-DICOMACTIVATE-', 
                              visible = False
                              ) )

toggle_layer = sg.pin(sg.Frame("Optimisation component toggle",
                [ [sg.Button("Create new default generate_allproc file",enable_events=True, key='-DUPGENPROC-',disabled=False,font=('Helvetica', 14),disabled_button_color='grey',size=(35,1)),
                    sg.Button("Create new default multiproc file",enable_events=True,key='-DUPMULPROC-',disabled=False,font=('Helvetica', 14),disabled_button_color='grey',size=(35,1))],  
                  [sg.Text('ChamberPlugCentre',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['ChamberPlugCentre'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['ChamberPlugCentre'] else 'white on red', key='-CPCTOG-'),
                    sg.Text('ChamberPlugTop',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['ChamberPlugTop'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['ChamberPlugTop'] else 'white on red', key='-CPTTOG-'),
                    sg.Text('ChamberPlugBottom',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['ChamberPlugBottom'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['ChamberPlugBottom'] else 'white on red', key='-CPBTOG-'),
                    sg.Text('ChamberPlugLeft',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['ChamberPlugLeft'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['ChamberPlugLeft'] else 'white on red', key='-CPLTOG-')],
                  [sg.Text('ChamberPlugRight',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['ChamberPlugRight'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['ChamberPlugRight'] else 'white on red', key='-CPRTOG-'),
                    sg.Text('ChamberPlugDose_tle',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['ChamberPlugDose_tle'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['ChamberPlugDose_tle'] else 'white on red', key='-TLETOG-'),
                    sg.Text('ChamberPlugDose_dtm',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['ChamberPlugDose_dtm'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['ChamberPlugDose_dtm'] else 'white on red', key='-DTMTOG-'),
                    sg.Text('ChamberPlugDose_dtw',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['ChamberPlugDose_dtw'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['ChamberPlugDose_dtw'] else 'white on red', key='-DTWTOG-')],
                  [sg.Text('CollimatorsVertical',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['CollimatorsVertical'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['CollimatorsVertical'] else 'white on red', key='-COLLVERTOG-'),
                    sg.Text('CollimatorsHorizontal',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['CollimatorsHorizontal'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['CollimatorsHorizontal'] else 'white on red', key='-COLLHORTOG-'),
                    sg.Text('TitaniumFilter',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['TitaniumFilter'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['TitaniumFilter'] else 'white on red', key='-TITFILTOG-'),
                    sg.Text('BowtieFilter',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['BowtieFilter'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['BowtieFilter'] else 'white on red', key='-BTFILTOG-')],
                  [sg.Text('Coll1',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['Coll1'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['Coll1'] else 'white on red', key='-COLL1TOG-'),
                    sg.Text('Coll2',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['Coll2'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['Coll2'] else 'white on red', key='-COLL2TOG-'),
                    sg.Text('Coll3',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['Coll3'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['Coll3'] else 'white on red', key='-COLL3TOG-'),
                    sg.Text('Coll4',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['Coll4'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['Coll4'] else 'white on red', key='-COLL4TOG-')],
                 
                  [sg.Text('DemoFlat',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['DemoFlat'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['DemoFlat'] else 'white on red', key='-DEMOFLATTOG-'),
                    sg.Text('DemoRTrap',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['DemoRTrap'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['DemoRTrap'] else 'white on red', key='-DEMORTRAPTOG-'),
                    sg.Text('DemoLTrap',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['DemoLTrap'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['DemoLTrap'] else 'white on red', key='-DEMOLTRAPTOG-')],
                  [sg.Text('topsidebox',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['topsidebox'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['topsidebox'] else 'white on red', key='-TSBTOG-'),
                    sg.Text('bottomsidebox',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['bottomsidebox'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['bottomsidebox'] else 'white on red', key='-BSBTOG-'),
                    sg.Text('couch',size = (21,1),font=('Helvetica', 12), text_color='black'),
                    sg.Button('On' if selectcomponents['couch'] else 'Off' , size=(3, 1), button_color='white on green' if selectcomponents['couch'] else 'white on red', key='-COHTOG-')]
                ]
                , key ='-USERACTIVATE-', visible = False))

CTDI_layer = sg.Frame('CTDI',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='TsCylinder',key='-CTDI_TYPE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='PMMA',key='-CTDI_MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CTDI_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='8.0',key='-CTDI_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='7.25',key='-CTDI_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0.",key='-CTDI_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360.',key='-CTDI_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.',key='-CTDI_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.',key='-CTDI_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.',key='-CTDI_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90',key='-CTDI_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])


ChamberPlugCentre_layer = sg.Frame('ChamberPlugCentre',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='TsCylinder',key='-CPC_TYPE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='PMMA',key='-CPC_MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPC_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.655',key='-CPC_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='5.0',key='-CPC_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0.",key='-CPC_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360.',key='-CPC_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPC_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPC_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPC_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90',key='-CPC_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugTop_layer = sg.Frame('ChamberPlugTop',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='TsCylinder',key='-CPT_TYPE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='PMMA',key='-CPT_MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPT_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.655',key='-CPT_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='5.0',key='-CPT_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0.",key='-CPT_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360.',key='-CPT_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPT_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPT_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-7.0',key='-CPT_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90',key='-CPT_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugBottom_layer = sg.Frame('ChamberPlugBottom',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='TsCylinder',key='-CPB_TYPE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='PMMA',key='-CPB_MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPB_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.655',key='-CPB_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='5.0',key='-CPB_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0.",key='-CPB_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360.',key='-CPB_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPB_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPB_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='7.0',key='-CPB_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90',key='-CPB_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugLeft_layer = sg.Frame('ChamberPlugLeft',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='TsCylinder',key='-CPL_TYPE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='PMMA',key='-CPL_MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPL_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.655',key='-CPL_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='5.0',key='-CPL_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0.",key='-CPL_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360.',key='-CPL_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-7.0',key='-CPL_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPL_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPL_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90',key='-CPL_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugRight_layer = sg.Frame('ChamberPlugRight',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='TsCylinder',key='-CPR_TYPE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='PMMA',key='-CPR_MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPR_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.655',key='-CPR_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='5.0',key='-CPR_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0.",key='-CPR_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360.',key='-CPR_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='7.0',key='-CPR_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPR_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0',key='-CPR_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90',key='-CPR_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],

                    ])

Scoring_layer = sg.Frame("Scoring",
                [
                   [sg.Text('TLE_Zbins',size = (10,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100',key='-TLEZB-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('DTM_Zbins',size = (10,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100',key='-DTMZB-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('DTW_Zbins',size = (10,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100',key='-DTWZB-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Physics_layer = sg.Frame("Physics",
                [
                   [sg.Text('List',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Default',key='-PHYLST-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Process',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='False',key='-PHYPRO-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Default Type',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Geant4_Modular',key='-PHYDEFTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Default Modules',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='6 "g4em-standard_opt4" "g4h-phy_QGSP_BIC_HP" "g4decay" "g4ion-binarycascade" "g4h-elastic_HP" "g4stopping"',key='-PHYDEFMO-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('EMRangeMin',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100.',key='-PHYEMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('EMRangeMax',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='521.',key='-PHYEMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

RotationGroup_layer = sg.Frame("Rotation Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-ROTTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='World',key='-ROTPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-ROTROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Tf_Rotate_Value',key='-ROTROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-ROTROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-ROTTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-ROTTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-ROTTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

CollimatorVerticalGroup_layer = sg.Frame("Collimators Vertical Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-COLLVERTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Rotation',key='-COLLVERPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-COLLVERROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-COLLVERROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-COLLVERROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='9.3',key='-COLLVERTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

CollimatorHorizontalGroup_layer = sg.Frame("Collimators Horizontal Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-COLLHORTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsVertical',key='-COLLHORPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-COLLHORROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-COLLHORROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-COLLHORROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1.4',key='-COLLHORTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

# SteelGroup_layer = sg.Frame("Steel Filter Group",
#               [
#                  [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='Group',key='-STEELTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='CollimatorsHorizontal',key='-STEELPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='1.59',key='-STEELTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#               ])

TitaniumGroup_layer = sg.Frame("Titanium Filter Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-TITTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsHorizontal',key='-TITPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TITROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TITROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TITROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1.59',key='-TITTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])
Bowtie_layer = sg.Frame("Bowtie Filter Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-BFTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsHorizontal',key='-BFPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-BFROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-BFROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90.',key='-BFROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-BFTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-BFTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='3.85',key='-BFTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Coll1_layer = sg.Frame("Collimator 1",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll1TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Lead',key='-Coll1MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsVertical',key='-Coll1PAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-Coll1ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90.',key='-Coll1ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll1ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll1TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='5.27',key='-Coll1TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll1TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='12.',key='-Coll1LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.3',key='-Coll1LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll1LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='9.2',key='-Coll1LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll2_layer = sg.Frame("Collimator 2",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll2TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Lead',key='-Coll2MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsVertical',key='-Coll2PAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90',key='-Coll2ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='270.',key='-Coll2ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll2ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll2TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-5.27',key='-Coll2TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll2TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='12.',key='-Coll2LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.3',key='-Coll2LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll2LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='9.2',key='-Coll2LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])
	
Coll3_layer = sg.Frame("Collimator 3",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll3TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Lead',key='-Coll3MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsHorizontal',key='-Coll3PAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-Coll3ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='180.',key='-Coll3ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll3ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='5.27',key='-Coll3TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-Coll3TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-Coll3TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='12.',key='-Coll3LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.3',key='-Coll3LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll3LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='9.2',key='-Coll3LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll4_layer = sg.Frame("Collimator 4",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll4TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Lead',key='-Coll4MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsHorizontal',key='-Coll4PAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-Coll4ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-Coll4ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll4ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-5.27',key='-Coll4TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-Coll4TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-Coll4TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='12.',key='-Coll4LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.3',key='-Coll4LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll4LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='9.2',key='-Coll4LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll1steel_layer = sg.Frame("Collimator Steel 1",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll1steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Steel',key='-Coll1steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsVertical',key='-Coll1steelPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-Coll1steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90.',key='-Coll1steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll1steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll1steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-Coll1steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-0.25',key='-Coll1steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='12.',key='-Coll1steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-Coll1steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll1steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll1steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll2steel_layer = sg.Frame("Collimator Steel 2",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll2steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Steel',key='-Coll2steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsVertical',key='-Coll2steelPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-Coll2steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='270.',key='-Coll2steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll2steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll2steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-Coll2steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-0.25',key='-Coll2steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='12.',key='-Coll2steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-Coll2steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll2steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll2steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll3steel_layer = sg.Frame("Collimator Steel 3",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll3steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Steel',key='-Coll3steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsHorizontal',key='-Coll3steelPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-Coll3steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='180.',key='-Coll3steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll3steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-Coll3steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll3steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-0.25',key='-Coll3steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='12.',key='-Coll3steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-Coll3steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll3steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll3steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll4steel_layer = sg.Frame("Collimator Steel 4",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll4steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Steel',key='-Coll4steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='CollimatorsHorizontal',key='-Coll4steelPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-Coll4steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-Coll4steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll4steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-Coll4steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-Coll4steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-0.25',key='-Coll4steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='12.',key='-Coll4steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-Coll4steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll4steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-Coll4steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])


# SteelFil_layer = sg.Frame("Steel Filter",
#               [
#                  [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='TsBox',key='-STEELFILTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='Steel',key='-STEELFILMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='SteelFilterGroup',key='-STEELFILPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.01',key='-STEELFILHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='10.',key='-STEELFILHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='10.',key='-STEELFILHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
#               ])

TITFIL_layer = sg.Frame("Titanium Filter",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-TITFILTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Titanium',key='-TITFILMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TitaniumFilterGroup',key='-TITFILPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TITFILROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TITFILROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TITFILROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TITFILTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TITFILTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TITFILTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0445',key='-TITFILHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-TITFILHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='10.',key='-TITFILHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

DemoFlat_layer = sg.Frame("Demo Flat",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-DEMOFLATTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-DEMOFLATMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='BowtieFilter',key='-DEMOFLATPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-DEMOFLATROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-DEMOFLATROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-DEMOFLATROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-DEMOFLATTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-DEMOFLATTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-DEMOFLATTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='7.5',key='-DEMOFLATHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.4',key='-DEMOFLATHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='7.5',key='-DEMOFLATHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])
TopSideBox_layer = sg.Frame("Top side box",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-TSBTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-TSBMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='BowtieFilter',key='-TSBPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TSBROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-TSBROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-TSBROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-TSBTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='5.0',key='-TSBTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1.3',key='-TSBTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='7.5',key='-TSBHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2.5',key='-TSBHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1.4',key='-TSBHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

BottomSideBox_layer = sg.Frame("Bottom side box",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-BSBTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-BSBMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='BowtieFilter',key='-BSBPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-BSBROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90.',key='-BSBROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-BSBROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-BSBTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-5.0',key='-BSBTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1.3',key='-BSBTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='7.5',key='-BSBHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2.5',key='-BSBHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1.4',key='-BSBHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

DemoRTrap_layer = sg.Frame("Demo RTrap",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-DEMORTRAPTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-DEMORTRAPMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='BowtieFilter',key='-DEMORTRAPPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-DEMORTRAPROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90',key='-DEMORTRAPROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-DEMORTRAPROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-DEMORTRAPTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-2.5',key='-DEMORTRAPTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.65',key='-DEMORTRAPTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='15.',key='-DEMORTRAPLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='5.',key='-DEMORTRAPLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2.8',key='-DEMORTRAPLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-DEMORTRAPLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])
DemoLTrap_layer = sg.Frame("Demo LTrap",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-DEMOLTRAPTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-DEMOLTRAPMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='BowtieFilter',key='-DEMOLTRAPPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='180',key='-DEMOLTRAPROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='270',key='-DEMOLTRAPROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-DEMOLTRAPROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-DEMOLTRAPTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2.5',key='-DEMOLTRAPTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.65',key='-DEMOLTRAPTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='15.',key='-DEMOLTRAPLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='5.0',key='-DEMOLTRAPLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2.8',key='-DEMOLTRAPLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.2',key='-DEMOLTRAPLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Couch_layer = sg.Frame("Couch",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-COUCHTY-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                     sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-COUCHMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='World',key='-COUCHPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-COUCHTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0',key='-COUCHTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Ge/couch/HLZ + Ge/CTDI/RMax',key='-COUCHTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.075',key='-COUCHHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100.0',key='-COUCHHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='26.0',key='-COUCHHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

BeamGroup_layer = sg.Frame("Beam Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-BEAMGRPTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Parent',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Rotation',key='-BEAMGRPPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-BEAMGRPTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-BEAMGRPTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-100.',key='-BEAMGRPTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-BEAMGRPROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-BEAMGRPROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.',key='-BEAMGRPROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                 
                ])

Beam_layer = sg.Frame("Beam",
                [   
                   [sg.Text('EnergySpec',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Continuous',key='-BEAMSPECTY-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('Type',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Beam',key='-BEAMTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Component',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='BeamPosition',key='-BEAMCOMPO-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('Particle',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='gamma',key='-BEAMPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('PosDistro',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Gaussian',key='-BEAMPOSDISTRO-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('CutOffShape',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Rectangle',key='-BEAMPOSHAPE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('CutOffX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='5.',key='-BEAMPOSCUTOFFX-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('CutOffY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='5.',key='-BEAMPOSCUTTOFFY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('SpreadX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.04246',key='-BEAMPOSSPRDX-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('SpreadY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.04246',key='-BEAMPOSSPRDY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('AngDistro',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Gaussian',key='-BEAMSPOSANGDISTRO-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('AngCutoffX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90',key='-BEAMPOSANGCUTOFFX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('AngCutoffY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90',key='-BEAMPOSANGCUTOFFY-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('AngSpreadX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='28',key='-BEAMPOSANGSPREADX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('AngSpreadY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='28',key='-BEAMPOSANGSPREADY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Time_layer = sg.Frame("Time Feature",
                [   
                   [sg.Text('Seq Time',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='501',key='-TIMESEQ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Verbosity',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-TIMEVERBO-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Timeline End',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='501.0',key='-TIMELINEEND-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Rotate Func',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Linear deg',key='-TIMEROTFUNC-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Rotate Rate',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.4',key='-TIMEROTRATE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Rotate Start',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90.0',key='-TIMEROTSTART-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('ShowHistoryInt',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100000',key='-TIMEHISTINT-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                     
                ])

                