# MC-DCaRE CTDI calibration: 125 kV Full Fan (Pelvis Spotlight)
general:
  g4_data_directory: /home/bchcphysics/Applications/GEANT4/G4DATA
  topas_directory: /home/bchcphysics/Applications/TOPAS/OpenTOPAS-build/topas
  seed: '9'
  threads: '20'
  histories: '5000000'
  dose_calibration_factor: '1.0'
  log_filename: simulation.log
imaging:
  simulation_type: CTDI
  rotation_direction: CBCT Clockwise
  imaging_mode: Pelvis Spotlight
  sequential_times: '100'
  time_verbosity: '0'
ctdi:
  dose_to_medium_zbins: '100'
  tle_zbins: '100'
  dose_to_water_zbins: '100'
  couch_enabled: true
  couch_width: 260. mm
  couch_thickness: 0.4 mm
  couch_length: 1000 mm
  user_blade_enabled: false
  graphics_enabled: false
