"""Varian TrueBeam kV imaging-mode parameter lookup tables.

Exports :class:`ImagingMode` and the :data:`IMAGING_MODES` dictionary keyed by
``"<direction>_<protocol>"`` strings.

Note: CBCT ``rotation_rate`` values (0.4 deg/s) are simulation-specific sampling
parameters, not clinical rotation speeds. Clinical TrueBeam CBCT uses 1.5-6.0 deg/s
(Mao et al. 2018). kV-kV ``rotation_rate`` (90 deg/s) represents the angle difference
between two discrete static exposures, not an actual rotation speed.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict


@dataclass(frozen=True)
class ImagingMode:
    """Immutable set of beam and collimator parameters for a single imaging preset."""

    rotation_rate: str
    voltage: str
    exposure: str
    fan_mode: str
    timeline_end: str
    field_x1: str
    field_x2: str
    field_y1: str
    field_y2: str
    blade_x1: str
    blade_x2: str
    blade_y1: str
    blade_y2: str
    ctdi_phantom: str
    dose_factor: str
    start_angle: str
    fan_detail: str
    no_projections: str
    proj_increment: str
    acquisition_time: str
    ctdiw_reference: str


# Full Fan blade openings (small field)
_FF_BX1 = "6.175536078965273 cm"
_FF_BX2 = "-6.175536078965273 cm"
_FF_BY1 = "5.814471115800571 cm"
_FF_BY2 = "-5.814471115800571 cm"

# Half Fan blade openings (large field)
_HF_BX1 = "6.94034206943498 cm"
_HF_BX2 = "-5.410730088495566 cm"
_HF_BY1 = "5.814471115800571 cm"
_HF_BY2 = "-5.814471115800571 cm"

# kV-kV blade openings
_KV_BX1 = "6.1183543226684725 cm"
_KV_BX2 = "-6.1183543226684725 cm"
_KV_BY1 = "5.768414666314948 cm"
_KV_BY2 = "-5.768414666314948 cm"

# kV-kV new-field sentinel values (8 values appended to each kV-kV tuple)
_KV_NEW = ("N/A", "N/A", "0 deg", "N/A", "N/A", "N/A", "N/A", "N/A")

_IMAGING_MODES_DATA: Dict[str, tuple] = {
    # ── Existing CBCT Clockwise (7) ──────────────────────────────────────────
    "CBCT Clockwise_Image Gently": (
        "0.4 deg/s",
        "80 kV",
        "100.2 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "0.9 mGy",
    ),
    "CBCT Clockwise_Head": (
        "0.4 deg/s",
        "100 kV",
        "150.3 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "3.2 mGy",
    ),
    "CBCT Clockwise_Short Thorax": (
        "0.4 deg/s",
        "125 kV",
        "210 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "680",
        "0.5 deg",
        "340 s",
        "TBD",
    ),
    "CBCT Clockwise_Spotlight": (
        "0.4 deg/s",
        "125 kV",
        "750 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "680",
        "0.5 deg",
        "340 s",
        "TBD",
    ),
    "CBCT Clockwise_Thorax": (
        "0.4 deg/s",
        "125 kV",
        "268.5 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "4.0 mGy",
    ),
    "CBCT Clockwise_Pelvis": (
        "0.4 deg/s",
        "125 kV",
        "1074.0 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "15.9 mGy",
    ),
    "CBCT Clockwise_Pelvis Large": (
        "0.4 deg/s",
        "140 kV",
        "1700.5 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "37.1 mGy",
    ),
    # ── Existing CBCT Anticlockwise (7) ──────────────────────────────────────
    "CBCT Anticlockwise_Image Gently": (
        "-0.4 deg/s",
        "80 kV",
        "100.2 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "0.9 mGy",
    ),
    "CBCT Anticlockwise_Head": (
        "-0.4 deg/s",
        "100 kV",
        "150.3 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "3.2 mGy",
    ),
    "CBCT Anticlockwise_Short Thorax": (
        "-0.4 deg/s",
        "125 kV",
        "210 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "680",
        "0.5 deg",
        "340 s",
        "TBD",
    ),
    "CBCT Anticlockwise_Spotlight": (
        "-0.4 deg/s",
        "125 kV",
        "750 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "680",
        "0.5 deg",
        "340 s",
        "TBD",
    ),
    "CBCT Anticlockwise_Thorax": (
        "-0.4 deg/s",
        "125 kV",
        "268.5 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "4.0 mGy",
    ),
    "CBCT Anticlockwise_Pelvis": (
        "-0.4 deg/s",
        "125 kV",
        "1074.0 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "15.9 mGy",
    ),
    "CBCT Anticlockwise_Pelvis Large": (
        "-0.4 deg/s",
        "140 kV",
        "1700.5 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "37.1 mGy",
    ),
    # ── kV-kV protocols (7) ──────────────────────────────────────────────────
    # Static pair: all use 13.2 x 9.9 cm fields and Full Fan bowtie.
    "kV-kV_Image Gently": (
        "90 deg/s",
        "80 kV",
        "100 mAs",
        "Full Fan",
        "2 s",
        "13.2 cm",
        "13.2 cm",
        "9.9 cm",
        "9.9 cm",
        _KV_BX1,
        _KV_BX2,
        _KV_BY1,
        _KV_BY2,
        *_KV_NEW,
    ),
    "kV-kV_Head": (
        "90 deg/s",
        "100 kV",
        "150 mAs",
        "Full Fan",
        "2 s",
        "13.2 cm",
        "13.2 cm",
        "9.9 cm",
        "9.9 cm",
        _KV_BX1,
        _KV_BX2,
        _KV_BY1,
        _KV_BY2,
        *_KV_NEW,
    ),
    "kV-kV_Short Thorax": (
        "90 deg/s",
        "125 kV",
        "210 mAs",
        "Full Fan",
        "2 s",
        "13.2 cm",
        "13.2 cm",
        "9.9 cm",
        "9.9 cm",
        _KV_BX1,
        _KV_BX2,
        _KV_BY1,
        _KV_BY2,
        *_KV_NEW,
    ),
    "kV-kV_Spotlight": (
        "90 deg/s",
        "125 kV",
        "750 mAs",
        "Full Fan",
        "2 s",
        "13.2 cm",
        "13.2 cm",
        "9.9 cm",
        "9.9 cm",
        _KV_BX1,
        _KV_BX2,
        _KV_BY1,
        _KV_BY2,
        *_KV_NEW,
    ),
    "kV-kV_Thorax": (
        "90 deg/s",
        "125 kV",
        "270 mAs",
        "Full Fan",
        "2 s",
        "13.2 cm",
        "13.2 cm",
        "9.9 cm",
        "9.9 cm",
        _KV_BX1,
        _KV_BX2,
        _KV_BY1,
        _KV_BY2,
        *_KV_NEW,
    ),
    "kV-kV_Pelvis": (
        "90 deg/s",
        "125 kV",
        "1080 mAs",
        "Full Fan",
        "2 s",
        "13.2 cm",
        "13.2 cm",
        "9.9 cm",
        "9.9 cm",
        _KV_BX1,
        _KV_BX2,
        _KV_BY1,
        _KV_BY2,
        *_KV_NEW,
    ),
    "kV-kV_Pelvis Large": (
        "90 deg/s",
        "140 kV",
        "1688 mAs",
        "Full Fan",
        "2 s",
        "13.2 cm",
        "13.2 cm",
        "9.9 cm",
        "9.9 cm",
        _KV_BX1,
        _KV_BX2,
        _KV_BY1,
        _KV_BY2,
        *_KV_NEW,
    ),
    # ── New CBCT Clockwise protocols (13) ─────────────────────────────────────
    "CBCT Clockwise_4D Spotlight": (
        "0.4 deg/s",
        "125 kV",
        "373.6 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "467",
        "0.771 deg",
        "67 s",
        "6.1 mGy",
    ),
    "CBCT Clockwise_4D Thorax": (
        "0.4 deg/s",
        "125 kV",
        "671.2 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "840",
        "0.429 deg",
        "120 s",
        "9.9 mGy",
    ),
    "CBCT Clockwise_Abdomen": (
        "0.4 deg/s",
        "125 kV",
        "716.0 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "10.6 mGy",
    ),
    "CBCT Clockwise_Abdo Spotlight": (
        "0.4 deg/s",
        "125 kV",
        "400.8 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "6.6 mGy",
    ),
    "CBCT Clockwise_Breast 360": (
        "0.4 deg/s",
        "125 kV",
        "89.5 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "1.3 mGy",
    ),
    "CBCT Clockwise_Extremity Spotlight": (
        "0.4 deg/s",
        "100 kV",
        "150.3 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "3.2 mGy",
    ),
    "CBCT Clockwise_Head and Shoulders": (
        "0.4 deg/s",
        "125 kV",
        "268.5 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "4.0 mGy",
    ),
    "CBCT Clockwise_Head SRS": (
        "0.4 deg/s",
        "100 kV",
        "537.0 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "900",
        "0.400 deg",
        "60 s",
        "11.3 mGy",
    ),
    "CBCT Clockwise_Paediatric Body": (
        "0.4 deg/s",
        "80 kV",
        "100.2 mAs",
        "Full Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "0.9 mGy",
    ),
    "CBCT Clockwise_Paediatric Head": (
        "0.4 deg/s",
        "80 kV",
        "50.1 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "0.5 mGy",
    ),
    "CBCT Clockwise_Pelvis Spotlight": (
        "0.4 deg/s",
        "125 kV",
        "751.5 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "12.3 mGy",
    ),
    "CBCT Clockwise_SBRT Spine": (
        "0.4 deg/s",
        "125 kV",
        "358.0 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "5.3 mGy",
    ),
    "CBCT Clockwise_Thorax Spotlight": (
        "0.4 deg/s",
        "125 kV",
        "150.3 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "2.5 mGy",
    ),
    # ── New CBCT Anticlockwise protocols (13) ─────────────────────────────────
    "CBCT Anticlockwise_4D Spotlight": (
        "-0.4 deg/s",
        "125 kV",
        "373.6 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "467",
        "0.771 deg",
        "67 s",
        "6.1 mGy",
    ),
    "CBCT Anticlockwise_4D Thorax": (
        "-0.4 deg/s",
        "125 kV",
        "671.2 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "840",
        "0.429 deg",
        "120 s",
        "9.9 mGy",
    ),
    "CBCT Anticlockwise_Abdomen": (
        "-0.4 deg/s",
        "125 kV",
        "716.0 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "10.6 mGy",
    ),
    "CBCT Anticlockwise_Abdo Spotlight": (
        "-0.4 deg/s",
        "125 kV",
        "400.8 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "6.6 mGy",
    ),
    "CBCT Anticlockwise_Breast 360": (
        "-0.4 deg/s",
        "125 kV",
        "89.5 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "1.3 mGy",
    ),
    "CBCT Anticlockwise_Extremity Spotlight": (
        "-0.4 deg/s",
        "100 kV",
        "150.3 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "3.2 mGy",
    ),
    "CBCT Anticlockwise_Head and Shoulders": (
        "-0.4 deg/s",
        "125 kV",
        "268.5 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "4.0 mGy",
    ),
    "CBCT Anticlockwise_Head SRS": (
        "-0.4 deg/s",
        "100 kV",
        "537.0 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "900",
        "0.400 deg",
        "60 s",
        "11.3 mGy",
    ),
    "CBCT Anticlockwise_Paediatric Body": (
        "-0.4 deg/s",
        "80 kV",
        "100.2 mAs",
        "Full Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "0.9 mGy",
    ),
    "CBCT Anticlockwise_Paediatric Head": (
        "-0.4 deg/s",
        "80 kV",
        "50.1 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "16 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "0.5 mGy",
    ),
    "CBCT Anticlockwise_Pelvis Spotlight": (
        "-0.4 deg/s",
        "125 kV",
        "751.5 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "12.3 mGy",
    ),
    "CBCT Anticlockwise_SBRT Spine": (
        "-0.4 deg/s",
        "125 kV",
        "358.0 mAs",
        "Half Fan",
        "900 s",
        "24.7 cm",
        "3.3 cm",
        "10.7 cm",
        "10.7 cm",
        _HF_BX1,
        _HF_BX2,
        _HF_BY1,
        _HF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Half Fan",
        "900",
        "0.400 deg",
        "60 s",
        "5.3 mGy",
    ),
    "CBCT Anticlockwise_Thorax Spotlight": (
        "-0.4 deg/s",
        "125 kV",
        "150.3 mAs",
        "Full Fan",
        "501 s",
        "14 cm",
        "14 cm",
        "10.7 cm",
        "10.7 cm",
        _FF_BX1,
        _FF_BX2,
        _FF_BY1,
        _FF_BY2,
        "32 cm",
        "1.0",
        "0 deg",
        "Full Fan",
        "500",
        "0.720 deg",
        "33 s",
        "2.5 mGy",
    ),
}

IMAGING_MODES: Dict[str, ImagingMode] = {
    key: ImagingMode(*data) for key, data in _IMAGING_MODES_DATA.items()
}
