# This sets up the default values for the GUI. Makes it easier to reference and make edits. 
# default_ = 


default_G4_Directory = '/root/G4Data'
default_TOPAS_Directory = '/root/topas/bin/topas '
default_Seed = '9'
default_Threads  = '4'
default_Histories = '100000'

# DICOM specific stuff
default_DICOM_Directory = '/root/nccs/Topas_wrapper/test/sampledicom/cherylair'
default_DICOM_RP_file = '/root/nccs/Topas_wrapper/test/sampledicom/cherylair/RP.Cheryl Phantom CTDI.Physics.dcm'
default_DICOM_TRANS_X = '0. mm'
default_DICOM_TRANS_Y = '0. mm'
default_DICOM_TRANS_Z = '0. mm'
default_DICOM_ROT_X = '-90. deg'
default_DICOM_ROT_Y = '0. deg'
default_DICOM_ROT_Z = '0. deg'
default_DICOM_IMAGE_START_ANGLE = '0 deg'
default_DICOM_IMAGE_STOP_ANGLE = '0 deg'
default_DICOM_IMAGE_VOLTAGE = '100 kV'
default_DICOM_BEAM_CURRENT = 'PLACEHOLDER'
default_DICOM_ISOCENTER_X = '0. mm'
default_DICOM_ISOCENTER_Y = '0. mm'
default_DICOM_ISOCENTER_Z = '0. mm'

#For CTDI
default_CTDI_PHANTOM_RMIN = '0.0 mm'
default_CTDI_PHANTOM_RMAX = '80. mm'
default_CTDI_PHANTOM_HL = '72.5 mm'
default_CTDI_PHANTOM_SPHI = "0. deg"
default_CTDI_PHANTOM_DPHI = '360. deg'
default_CTDI_PHANTOM_TRANS_X = '0. mm'
default_CTDI_PHANTOM_TRANS_Y = '0. mm'
default_CTDI_PHANTOM_TRANS_Z = '0. mm'
default_CTDI_PHANTOM_ROT_X = '-90 deg'

default_CTDI_CENTER_PLUG_RMIN = '0.0 mm'
default_CTDI_CENTER_PLUG_RMAX = '6.55 mm'
default_CTDI_CENTER_PLUG_HL = '50. mm'
default_CTDI_CENTER_PLUG_SPHI = "0. deg"
default_CTDI_CENTER_PLUG_DPHI = '360. deg'
default_CTDI_CENTER_PLUG_TRANS_X = '0.0 mm'
default_CTDI_CENTER_PLUG_TRANS_Y = '0.0 mm'
default_CTDI_CENTER_PLUG_TRANS_Z = '0.0 mm'
default_CTDI_CENTER_PLUG_ROT_X = '-90 deg'

default_CTDI_TOP_PLUG_RMIN = '0.0 mm'
default_CTDI_TOP_PLUG_RMAX = '6.55 mm'
default_CTDI_TOP_PLUG_HL = '50. mm'
default_CTDI_TOP_PLUG_SPHI = "0. deg"
default_CTDI_TOP_PLUG_DPHI = '360. deg'
default_CTDI_TOP_PLUG_TRANS_X = '0.0 mm'
default_CTDI_TOP_PLUG_TRANS_Y = '0.0 mm'
default_CTDI_TOP_PLUG_TRANS_Z = '-7.0 mm'
default_CTDI_TOP_PLUG_ROT_X = '-90 deg'

default_CTDI_BOTTOM_PLUG_RMIN = '0.0 mm'
default_CTDI_BOTTOM_PLUG_RMAX = '6.55 mm'
default_CTDI_BOTTOM_PLUG_HL = '50. mm'
default_CTDI_BOTTOM_PLUG_SPHI = "0. deg"
default_CTDI_BOTTOM_PLUG_DPHI = '360. deg'
default_CTDI_BOTTOM_PLUG_TRANS_X = '0.0 mm'
default_CTDI_BOTTOM_PLUG_TRANS_Y = '0.0 mm'
default_CTDI_BOTTOM_PLUG_TRANS_Z = '7.0 mm'
default_CTDI_BOTTOM_PLUG_ROT_X = '-90 deg'

default_CTDI_LEFT_PLUG_RMIN = '0.0 mm'
default_CTDI_LEFT_PLUG_RMAX = '6.55 mm'
default_CTDI_LEFT_PLUG_HL = '50. mm'
default_CTDI_LEFT_PLUG_SPHI = "0. deg"
default_CTDI_LEFT_PLUG_DPHI = '360. deg'
default_CTDI_LEFT_PLUG_TRANS_X = '-7.0 mm'
default_CTDI_LEFT_PLUG_TRANS_Y = '0.0 mm'
default_CTDI_LEFT_PLUG_TRANS_Z = '0.0 mm'
default_CTDI_LEFT_PLUG_ROT_X = '-90 deg'

default_CTDI_RIGHT_PLUG_RMIN = '0.0 mm'
default_CTDI_RIGHT_PLUG_RMAX = '6.55 mm'
default_CTDI_RIGHT_PLUG_HL = '50. mm'
default_CTDI_RIGHT_PLUG_SPHI = "0. deg"
default_CTDI_RIGHT_PLUG_DPHI = '360. deg'
default_CTDI_RIGHT_PLUG_TRANS_X = '7.0 mm'
default_CTDI_RIGHT_PLUG_TRANS_Y = '0.0 mm'
default_CTDI_RIGHT_PLUG_TRANS_Z = '0.0 mm'
default_CTDI_RIGHT_PLUG_ROT_X = '-90 deg'

default_DTM_Zbins = '100'
default_TLE_Zbins = '100'

default_PHYSICS_LIST = 'Default'
default_PHYSICS_PROCESS ='False'
default_PHYSICS_TYPE = 'Geant4_Modular'
default_PHYSICS_MODULES = '6 "g4em-standard_opt4" "g4h-phy_QGSP_BIC_HP" "g4decay" "g4ion-binarycascade" "g4h-elastic_HP" "g4stopping"'
default_PHYSICS_EM_MIN ='100. eV'
default_PHYSICS_EM_MAX ='521. MeV'

default_ROTATION_TYPE = 'Group'
default_ROTATION_ROT_X = '0. deg'
default_ROTATION_ROT_Y = 'Tf/Rotate/Value deg'
default_ROTATION_ROT_Z = '0. deg'
default_ROTATION_TRANS_X = '0.0 mm'
default_ROTATION_TRANS_Y = '0.0 mm'
default_ROTATION_TRANS_Z = '0.0 mm'

default_COLLVERT_TYPE = 'Group'
default_COLLVERT_ROT_X = '0 deg'
default_COLLVERT_ROT_Y = '0 deg'
default_COLLVERT_ROT_Z = '0 deg'
default_COLLVERT_TRANS_Z = '93. mm'

default_COLLHOR_TYPE = 'Group'
default_COLLHOR_ROT_X = '0 deg'
default_COLLHOR_ROT_Y = '0 deg'
default_COLLHOR_ROT_Z = '0 deg'
default_COLLHOR_TRANS_Z = '14. mm'

default_TIT_TYPE = 'Group'
default_TIT_ROT_X = '0 deg'
default_TIT_ROT_Y = '0 deg'
default_TIT_ROT_Z = '0 deg'
default_TIT_TRANS_Z = '1.59 mm'

default_BOW_TYPE = 'Group'
default_BOW_ROT_X = '0. deg'
default_BOW_ROT_Y = '0. deg'
default_BOW_ROT_Z = '90. deg'
default_BOW_TRANS_X = '0.0 mm'
default_BOW_TRANS_Y = '0.0 mm'
default_BOW_TRANS_Z = '38.5 mm'

default_COLL1_TYPE = 'G4RTrap'
default_COLL1_MATERIAL = 'Lead'
default_COLL1_ROT_X = '-90. deg'
default_COLL1_ROT_Y = '90. deg'
default_COLL1_ROT_Z = '0. deg'
default_COLL1_TRANS_X = '0. mm'
default_COLL1_TRANS_Y = '52.7 mm'
default_COLL1_TRANS_Z = '0. mm'
default_COLL1_LZ = '120. mm'
default_COLL1_LY = '3. mm'
default_COLL1_LX = '100. mm'
default_COLL1_LTX = '92. mm'

default_COLL2_TYPE = 'G4RTrap'
default_COLL2_MATERIAL = 'Lead'
default_COLL2_ROT_X = '-90. deg'
default_COLL2_ROT_Y = '270. deg'
default_COLL2_ROT_Z = '0. deg'
default_COLL2_TRANS_X = '0. mm'
default_COLL2_TRANS_Y = '-52.7 mm'
default_COLL2_TRANS_Z = '0. mm'
default_COLL2_LZ = '120. mm'
default_COLL2_LY = '3. mm'
default_COLL2_LX = '100. mm'
default_COLL2_LTX = '92. mm'

default_COLL3_TYPE = 'G4RTrap'
default_COLL3_MATERIAL = 'Lead'
default_COLL3_ROT_X = '-90. deg'
default_COLL3_ROT_Y = '180. deg'
default_COLL3_ROT_Z = '0. deg'
default_COLL3_TRANS_X = '52.7 mm'
default_COLL3_TRANS_Y = '0. mm'
default_COLL3_TRANS_Z = '0. mm'
default_COLL3_LZ = '120. mm'
default_COLL3_LY = '3. mm'
default_COLL3_LX = '100. mm'
default_COLL3_LTX = '92. mm'

default_COLL4_TYPE = 'G4RTrap'
default_COLL4_MATERIAL = 'Lead'
default_COLL4_ROT_X = '-90. deg'
default_COLL4_ROT_Y = '0. deg'
default_COLL4_ROT_Z = '0. deg'
default_COLL4_TRANS_X = '-52.7 mm'
default_COLL4_TRANS_Y = '0. mm'
default_COLL4_TRANS_Z = '0. mm'
default_COLL4_LZ = '120. mm'
default_COLL4_LY = '3. mm'
default_COLL4_LX = '100. mm'
default_COLL4_LTX = '92. mm'

default_COLL1_STEEL_TYPE = 'G4RTrap'
default_COLL1_STEEL_MATERIAL = 'Steel'
default_COLL1_STEEL_ROT_X = '-90. deg'
default_COLL1_STEEL_ROT_Y = '90. deg'
default_COLL1_STEEL_ROT_Z = '0. deg'
default_COLL1_STEEL_TRANS_X = '0. mm'
default_COLL1_STEEL_TRANS_Y = '2. mm'
default_COLL1_STEEL_TRANS_Z = '-2.5 mm'
default_COLL1_STEEL_LZ = '120. mm'
default_COLL1_STEEL_LY = '2. mm'
default_COLL1_STEEL_LX = '100. mm'
default_COLL1_STEEL_LTX = '100. mm'

default_COLL2_STEEL_TYPE = 'G4RTrap'
default_COLL2_STEEL_MATERIAL = 'Steel'
default_COLL2_STEEL_ROT_X = '-90. deg'
default_COLL2_STEEL_ROT_Y = '270. deg'
default_COLL2_STEEL_ROT_Z = '0. deg'
default_COLL2_STEEL_TRANS_X = '0. mm'
default_COLL2_STEEL_TRANS_Y = '2. mm'
default_COLL2_STEEL_TRANS_Z = '-2.5 mm'
default_COLL2_STEEL_LZ = '120. mm'
default_COLL2_STEEL_LY = '2. mm'
default_COLL2_STEEL_LX = '100. mm'
default_COLL2_STEEL_LTX = '100. mm'

default_COLL3_STEEL_TYPE = 'G4RTrap'
default_COLL3_STEEL_MATERIAL = 'Steel'
default_COLL3_STEEL_ROT_X = '-90. deg'
default_COLL3_STEEL_ROT_Y = '180. deg'
default_COLL3_STEEL_ROT_Z = '0. deg'
default_COLL3_STEEL_TRANS_X = '2. mm'
default_COLL3_STEEL_TRANS_Y = '0. mm'
default_COLL3_STEEL_TRANS_Z = '-2.5 mm'
default_COLL3_STEEL_LZ = '120. mm'
default_COLL3_STEEL_LY = '2. mm'
default_COLL3_STEEL_LX = '100. mm'
default_COLL3_STEEL_LTX = '100. mm'

default_COLL4_STEEL_TYPE = 'G4RTrap'
default_COLL4_STEEL_MATERIAL = 'Steel'
default_COLL4_STEEL_ROT_X = '-90. deg'
default_COLL4_STEEL_ROT_Y = '0. deg'
default_COLL4_STEEL_ROT_Z = '0. deg'
default_COLL4_STEEL_TRANS_X = '2. mm'
default_COLL4_STEEL_TRANS_Y = '0. mm'
default_COLL4_STEEL_TRANS_Z = '-2.5 mm'
default_COLL4_STEEL_LZ = '120. mm'
default_COLL4_STEEL_LY = '2. mm'
default_COLL4_STEEL_LX = '100. mm'
default_COLL4_STEEL_LTX = '100. mm'

default_TIT_FILTER_TYPE = 'TsBox'
default_TIT_FILTER_MATERIAL = 'Titanium'
default_TIT_FILTER_ROT_X = '0. deg'
default_TIT_FILTER_ROT_Y = '0. deg'
default_TIT_FILTER_ROT_Z = '0. deg'
default_TIT_FILTER_TRANS_X = '0. mm'
default_TIT_FILTER_TRANS_Y = '0. mm'
default_TIT_FILTER_TRANS_Z = '0. mm'
default_TIT_FILTER_HLZ = '0.445 mm'
default_TIT_FILTER_HLY = '100. mm'
default_TIT_FILTER_HLX = '100. mm'

default_FLAT_TYPE = 'TsBox'
default_FLAT_MATERIAL = 'Aluminum'
default_FLAT_ROT_X = '0. deg'
default_FLAT_ROT_Y = '-90. deg'
default_FLAT_ROT_Z = '0. deg'
default_FLAT_TRANS_X = '0. mm'
default_FLAT_TRANS_Y = '0. mm'
default_FLAT_TRANS_Z = '0. mm'
default_FLAT_HLZ = '75. mm'
default_FLAT_HLY = '1.7 mm'
default_FLAT_HLX = '1. mm'

default_TOP_BOX_TYPE = 'TsBox'
default_TOP_BOX_MATERIAL = 'Aluminum'
default_TOP_BOX_ROT_X = '0. deg'
default_TOP_BOX_ROT_Y = '-90. deg'
default_TOP_BOX_ROT_Z = '0. deg'
default_TOP_BOX_TRANS_X = '0. mm'
default_TOP_BOX_TRANS_Y = '50. mm'
default_TOP_BOX_TRANS_Z = '13. mm'
default_TOP_BOX_HLZ = '75. mm'
default_TOP_BOX_HLY = '25. mm'
default_TOP_BOX_HLX = '14. mm'

default_BOTTOM_BOX_TYPE = 'TsBox'
default_BOTTOM_BOX_MATERIAL = 'Aluminum'
default_BOTTOM_BOX_ROT_X = '0. deg'
default_BOTTOM_BOX_ROT_Y = '-90. deg'
default_BOTTOM_BOX_ROT_Z = '0. deg'
default_BOTTOM_BOX_TRANS_X = '0. mm'
default_BOTTOM_BOX_TRANS_Y = '-50. mm'
default_BOTTOM_BOX_TRANS_Z = '13. mm'
default_BOTTOM_BOX_HLZ = '75. mm'
default_BOTTOM_BOX_HLY = '25. mm'
default_BOTTOM_BOX_HLX = '14. mm'

default_RIGHT_TRAP_TYPE = 'G4RTrap'
default_RIGHT_TRAP_MATERIAL = 'Aluminum'
default_RIGHT_TRAP_ROT_X = '0. deg'
default_RIGHT_TRAP_ROT_Y = '90. deg'
default_RIGHT_TRAP_ROT_Z = '0. deg'
default_RIGHT_TRAP_TRANS_X = '0. mm'
default_RIGHT_TRAP_TRANS_Y = '-25. mm'
default_RIGHT_TRAP_TRANS_Z = '6.5 mm'
default_RIGHT_TRAP_LZ = '150. mm'
default_RIGHT_TRAP_LY = '50. mm'
default_RIGHT_TRAP_LX = '28. mm'
default_RIGHT_TRAP_LTX = '2. mm'

default_LEFT_TRAP_TYPE = 'G4RTrap'
default_LEFT_TRAP_MATERIAL = 'Aluminum'
default_LEFT_TRAP_ROT_X = '180. deg'
default_LEFT_TRAP_ROT_Y = '270. deg'
default_LEFT_TRAP_ROT_Z = '0. deg'
default_LEFT_TRAP_TRANS_X = '0. mm'
default_LEFT_TRAP_TRANS_Y = '25. mm'
default_LEFT_TRAP_TRANS_Z = '6.5 mm'
default_LEFT_TRAP_LZ = '150. mm'
default_LEFT_TRAP_LY = '50. mm'
default_LEFT_TRAP_LX = '28. mm'
default_LEFT_TRAP_LTX = '2. mm'

default_COUCH_TYPE = 'TsBox'
default_COUCH_MATERIAL = 'Aluminum'
default_COUCH_TRANS_X = '0. mm'
default_COUCH_TRANS_Y = '0. mm'
default_COUCH_TRANS_Z = 'Ge/couch/HLZ + Ge/CTDI/RMax mm'
default_COUCH_HLZ = '0.75 mm'
default_COUCH_HLY = '1000. mm'
default_COUCH_HLX = '260. mm'

default_BEAM_GROUP_TYPE = 'Group'
default_BEAM_GROUP_TRANS_X = '0. mm'
default_BEAM_GROUP_TRANS_Y = '0. mm'
default_BEAM_GROUP_TRANS_Z = '-1000. mm'
default_BEAM_GROUP_ROT_X = '0. deg'
default_BEAM_GROUP_ROT_Y = '0. deg'
default_BEAM_GROUP_ROT_Z = '0. deg'

default_BEAM_PARAMS_ENERGYSPEC = 'Continuous'
default_BEAM_PARAMS_TYPE = 'Beam'
default_BEAM_PARAMS_COMPONENT = 'BeamPosition'
default_BEAM_PARAMS_PARTICLE = 'gamma'
default_BEAM_PARAMS_POS_DISTRO = 'Gaussian'
default_BEAM_PARAMS_CUTOFF_SHAPE = 'Rectangle'
default_BEAM_PARAMS_CUTOFF_X = '50. mm'
default_BEAM_PARAMS_CUTOFF_Y = '50. mm'
default_BEAM_PARAMS_SPREAD_X = '0.4246 mm'
default_BEAM_PARAMS_SPREAD_Y = '0.4246 mm'
default_BEAM_PARAMS_ANG_DISTRO = 'Gaussian'
default_BEAM_PARAMS_ANG_CUTOFF_X = '90. deg'
default_BEAM_PARAMS_ANG_CUTOFF_Y = '90. deg'
default_BEAM_PARAMS_ANG_SPREAD_X = '28. deg'
default_BEAM_PARAMS_ANG_SPREAD_Y = '28. deg'

default_TIME_SEQ_TIME = '501'
default_TIME_VERBOSITY = '0'
default_TIME_TIME_END = '501.0 s'
default_TIME_ROT_FUNC = 'Linear deg'
default_TIME_ROT_RATE = '0.4 deg/s'
default_TIME_ROT_START = '90.0 deg'
default_TIME_ROT_HISTORY = '100000'
