import PySimpleGUI as sg
sg.theme('Reddit')

general_layer = sg.Frame('General Settings',
                [ 
                  [sg.Text('G4 Data Directory',size = (17,1),font=('Helvetica', 14), text_color='black'),
                    sg.In(default_text='/root/G4Data',key='-G4FOLDERNAME-',size=(50,1),font=('Helvetica', 14),enable_events=True),sg.FolderBrowse(button_text= "Browse", font=('Helvetica', 14))],
                  [sg.Text('TOPAS Directory',size =(17,1),font=('Helvetica', 14),text_color='black'),
                    sg.In(default_text='/root/topas/bin/topas ',key='-TOPAS-',size=(50,1),font=('Helvetica', 14),enable_events=True),sg.FileBrowse(button_text= "Browse",font=('Helvetica', 14))],
                  [sg.Text('Seed',size =(9,1),font=('Helvetica', 14),text_color='black'),
                    sg.In(default_text='9',key='-SEED-',size=(10,1),font=('Helvetica', 14),enable_events=True)],
                  [sg.Text('Threads',size = (9,1),font=('Helvetica', 14),text_color='black'),
                    sg.In(default_text='4',key='-THREAD-',size=(10,1),font=('Helvetica',14),enable_events=True)],
                  [sg.Text('Histories',size = (9,1),font=('Helvetica',14),text_color='black'),
                    sg.In(default_text='100000',key='-HIST-',size=(10,1),font=('Helvetica',14),enable_events=True),
                    sg.Push(),
                    sg.Button(button_text='Reset all parameters to default', key='-RESET-')],
              ])

main_menu_information_layer = sg.Frame('Instructions on the usage of the GUI', 
                             [ 
                               [sg.Text('Select your Topas and G4 data directories. Next, select the function you would like to enable. ')],
                               [sg.Text('   DICOM allows the user to specify a patient DICOM CT image folder to run simulations on')],
                               [sg.Text('   CTDI validation if for running simulations on CTDI phantom')],
                               [sg.Text('In the following pages, type in your desired value with the units. ')],
                               [sg.Text('By default all lengths are in units of mm and all angles are in units of degrees.')],
                             ]) 

runbuttons_layer= sg.Frame('Activate simulation', 
                           [
                             [sg.Checkbox("Graphics toggle", enable_events=True, key='-GRAPHICS-')],
                             [sg.Button("Run", enable_events=True, key='-RUN-', disabled=False, font=('Helvetica', 14), disabled_button_color='grey')],
                            ], key ='-BUTTONSACTIVATE-', 
                              visible = False)

function_layer = sg.Frame('Choose your function',
                          [
                            [sg.Checkbox('Use DICOM', enable_events=True, key='-DICOMACTIVATECHECK-'),
                             sg.Checkbox('CTDI validation', enable_events=True , key='-USERACTIVATECHECK-')
                             ],
                          ])

dicom_file_layer = sg.pin(sg.Frame("DICOM inputs",
                              [ 
                                [sg.Text('DICOM Directory',size =(17,1),font=('Helvetica', 14),text_color='black'),
                                 sg.In(default_text='dicom_path',key='-DICOM-',size=(50,1),font=('Helvetica', 14),enable_events=True),sg.FolderBrowse(font=('Helvetica', 14))
                                ],
                                [sg.Text('DICOM RP file',size =(17,1),font=('Helvetica', 14),text_color='black'),
                                 sg.In(default_text='dicom_RP_path',key='-DICOMRP-',size=(50,1),font=('Helvetica', 14),enable_events=True),sg.FileBrowse(file_types= (("DICOM File",'*.dcm'),) ,font=('Helvetica', 14))
                                ],
                                [sg.Button("Run set up imaging dose simulation",enable_events=True, key='-DICOMBAT-',font=('Helvetica', 14),size=(35,1))],
                              ],
                              key ='-DICOMACTIVATE-', 
                              visible = False
                              ) )

dicom_information_layer = sg.Frame('Instructions on the usage of the DICOM adjustments', 
                             [ 
                               [sg.Text('The programme automatically shifts the patient such that the isocentre of the treatment plan is matched to the isocentre of the beam.')],
                               [sg.Text('In the next page, make any adjustments relative to the ioscentre of the treatment plan.')],
                               [sg.Text('Use the other tabs to make edits to other parameters like collimator openings and beam current. ')],
                             ]) 

dicom_patient_layer = sg.Frame('Patient set up adjustments',
                    [
                        [sg.Text('TransX',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. mm',key='-DICOM_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. mm',key='-DICOM_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. mm',key='-DICOM_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90. deg',key='-DICOM_ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)], 
                        [sg.Text('RotY',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. deg',key='-DICOM_ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)], 
                        [sg.Text('RotZ',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. deg',key='-DICOM_ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)], 
                    ])

dicom_scan_layer = sg.Frame('Set up imaging parameters',
                    [
                        [sg.Text('Fan mode selection'),
                         sg.Combo(['Full fan', 'Half fan'],default_value='Full fan', key='-FAN-', readonly=True )],
                        [sg.Text('Start angle',size = (15,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0 deg',key='-DICOM_STARTROT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('Stop angle',size = (15,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0 deg',key='-DICOM_STOPROT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('Direction of rotation',size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.Combo(['Clockwise', 'Anticlockwise'], key='-DICOM_DIRECTROT-', readonly=True )],
                        [sg.Text('Beam current',size = (15,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='PLACEHOLDER',key='-DICOM_BEAMCURRENT-',size=(10,1), font=('Helvetica', 12), enable_events=True)], 
                    ])

dicom_planned_layer = sg.Frame('Treatment plan parameters',
                    [
                        [sg.Text('Isocenter X',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text= '0. mm', key='-DICOM_ISOX-',size=(10,1), font=('Helvetica', 12), background_color= 'light grey',enable_events=True)],
                        [sg.Text('Isocenter Y',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. mm', key='-DICOM_ISOY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('Isocenter Z',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. mm', key='-DICOM_ISOZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

toggle_layer = sg.pin(sg.Frame("Optimisation component toggle",
                [ [
                    sg.Checkbox("ChamberPlugCentre", default= True , enable_events=True, key='-CPCTOG-', expand_x=True),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("ChamberPlugTop", default= True , enable_events=True, key='-CPTTOG-', expand_x=True),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("ChamberPlugBottom", default= True , enable_events=True, key='-CPBTOG-', expand_x=True),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("ChamberPlugLeft", default= True , enable_events=True, key='-CPLTOG-', expand_x=True)
                  ],
                  [
                    sg.Checkbox("ChamberPlugRight", default= True , enable_events=True, key='-CPRTOG-', expand_x=True),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("ChamberPlugDose_dtm", default= True , enable_events=True, key='-DTMTOG-', expand_x=True),
                    sg.VerticalSeparator(),
                    sg.Checkbox("ChamberPlugDose_tle", default= True , enable_events=True, key='-TLETOG-', expand_x=True),
                    sg.VerticalSeparator(),
                    sg.Checkbox("ChamberPlugDose_dtw", default= True , enable_events=True, key='-DTWTOG-', expand_x=True)
                  ],
                  [
                    sg.Checkbox("CollimatorsVertical", default= True , enable_events=True, key='-COLLVERTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("CollimatorsHorizontal", default= True , enable_events=True, key='-COLLHORTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("TitaniumFilter", default= True , enable_events=True, key='-TITFILTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("BowtieFilter", default= True , enable_events=True, key='-BTFILTOG-')
                  ],
                  [
                    sg.Checkbox("Coll1", default= True , enable_events=True, key='-COLL1TOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("Coll2", default= True , enable_events=True, key='-COLL2TOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("Coll3", default= True , enable_events=True, key='-COLL3TOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("Coll4", default= True , enable_events=True, key='-COLL4TOG-')
                  ],
                  [
                    sg.Checkbox("DemoFlat", default= True , enable_events=True, key='-DEMOFLATTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("DemoRTrap", default= True , enable_events=True, key='-DEMORTRAPTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("DemoLTrap", default= True , enable_events=True, key='-DEMOLTRAPTOG-')
                  ],
                  [
                    sg.Checkbox("topsidebox", default= True , enable_events=True, key='-TSBTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("bottomsidebox", default= True , enable_events=True, key='-BSBTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("couch", default= True , enable_events=True, key='-COHTOG-')
                  ]
                ]
                , key ='-USERACTIVATE-', visible = False))

CTDI_information_layer = sg.Frame('Instructions on the usage of the CTDI phantom parameters', 
                             [ 
                               [sg.Text('Edit the parameters here to change between 16 cm and 32 cm phantoms.')],
                               [sg.Text('Simulation will automatically run 5 CTDI simulations for all 5 possible detector position.')],
                               [sg.Text('Use the other tabs to make edits to other parameters like collimator openings and beam current. ')],
                             ]) 
CTDI_layer = sg.Frame('CTDI phantom',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CTDI_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='80. mm',key='-CTDI_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='72.5 mm',key='-CTDI_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0. deg",key='-CTDI_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360. deg',key='-CTDI_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. mm',key='-CTDI_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. mm',key='-CTDI_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0. mm',key='-CTDI_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90 deg',key='-CTDI_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])


ChamberPlugCentre_layer = sg.Frame('ChamberPlugCentre',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPC_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='6.55 mm',key='-CPC_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='50. mm',key='-CPC_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0. deg ",key='-CPC_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360. deg',key='-CPC_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPC_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPC_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPC_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90 deg',key='-CPC_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugTop_layer = sg.Frame('ChamberPlugTop',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPT_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='6.55 mm',key='-CPT_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='50. mm',key='-CPT_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0. deg",key='-CPT_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360. deg',key='-CPT_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPT_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPT_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-7.0 mm',key='-CPT_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90 deg',key='-CPT_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugBottom_layer = sg.Frame('ChamberPlugBottom',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPB_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='6.55 mm',key='-CPB_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='50. mm',key='-CPB_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0. deg",key='-CPB_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360. deg',key='-CPB_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPB_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPB_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='7.0 mm',key='-CPB_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90 deg',key='-CPB_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugLeft_layer = sg.Frame('ChamberPlugLeft',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPL_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='6.55 mm',key='-CPL_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='50. mm',key='-CPL_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0. deg",key='-CPL_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360. deg',key='-CPL_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-7.0 mm',key='-CPL_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPL_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPL_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90 deg',key='-CPL_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugRight_layer = sg.Frame('ChamberPlugRight',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPR_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='6.55 mm',key='-CPR_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='50. mm',key='-CPR_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text="0. deg",key='-CPR_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='360. deg',key='-CPR_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='7.0 mm',key='-CPR_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPR_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='0.0 mm',key='-CPR_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text='-90 deg',key='-CPR_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],

                    ])

Scoring_layer = sg.Frame("Scoring",
                [
                   [sg.Text('DTM_Zbins',size = (10,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100',key='-DTMZB-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TLE_Zbins',size = (10,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100',key='-TLEZB-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                  #  [sg.Text('DTW_Zbins',size = (10,1),font=('Helvetica', 12), text_color='black'),
                  #    sg.In(default_text='100',key='-DTWZB-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Physics_layer = sg.Frame("Physics",
                [
                   [sg.Text('List',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Default',key='-PHYLST-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Process',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='False',key='-PHYPRO-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Default Type',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Geant4_Modular',key='-PHYDEFTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Default Modules',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='6 "g4em-standard_opt4" "g4h-phy_QGSP_BIC_HP" "g4decay" "g4ion-binarycascade" "g4h-elastic_HP" "g4stopping"',key='-PHYDEFMO-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('EMRangeMin',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. eV',key='-PHYEMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('EMRangeMax',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='521. MeV',key='-PHYEMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

RotationGroup_layer = sg.Frame("Rotation Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-ROTTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-ROTROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Tf/Rotate/Value deg',key='-ROTROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-ROTROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-ROTTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-ROTTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-ROTTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

CollimatorVerticalGroup_layer = sg.Frame("Collimators Vertical Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-COLLVERTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-COLLVERROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-COLLVERROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-COLLVERROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='93. mm',key='-COLLVERTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

CollimatorHorizontalGroup_layer = sg.Frame("Collimators Horizontal Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-COLLHORTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-COLLHORROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-COLLHORROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-COLLHORROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='14. mm',key='-COLLHORTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

# SteelGroup_layer = sg.Frame("Steel Filter Group",
#               [
#                  [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='Group',key='-STEELTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0. deg',key='-STEELROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0. deg',key='-STEELROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0. deg',key='-STEELROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='1.59 mm',key='-STEELTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#               ])

TitaniumGroup_layer = sg.Frame("Titanium Filter Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-TITTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-TITROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-TITROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-TITROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1.59 mm',key='-TITTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])
Bowtie_layer = sg.Frame("Bowtie Filter Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-BFTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-BFROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-BFROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90. deg',key='-BFROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-BFTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-BFTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='38.5 mm',key='-BFTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Coll1_layer = sg.Frame("Collimator 1",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll1TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Lead',key='-Coll1MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-Coll1ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90. deg',key='-Coll1ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-Coll1ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll1TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='52.7 mm',key='-Coll1TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll1TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='120. mm',key='-Coll1LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='3. mm',key='-Coll1LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll1LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='92. mm',key='-Coll1LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll2_layer = sg.Frame("Collimator 2",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll2TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Lead',key='-Coll2MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90 deg',key='-Coll2ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='270. deg',key='-Coll2ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-Coll2ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll2TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-52.7 mm',key='-Coll2TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll2TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='120. mm',key='-Coll2LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='3. mm',key='-Coll2LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll2LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='92. mm',key='-Coll2LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])
	
Coll3_layer = sg.Frame("Collimator 3",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll3TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Lead',key='-Coll3MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-Coll3ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='180. deg',key='-Coll3ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-Coll3ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='52.7 mm',key='-Coll3TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll3TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll3TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='120. mm',key='-Coll3LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='3. mm',key='-Coll3LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll3LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='92. mm',key='-Coll3LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll4_layer = sg.Frame("Collimator 4",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll4TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Lead',key='-Coll4MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-Coll4ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-Coll4ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0 deg',key='-Coll4ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-52.7 mm',key='-Coll4TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll4TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll4TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='120. mm',key='-Coll4LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='3. mm',key='-Coll4LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll4LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='92. mm',key='-Coll4LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll1steel_layer = sg.Frame("Collimator Steel 1",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll1steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Steel',key='-Coll1steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-Coll1steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90. deg',key='-Coll1steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-Coll1steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll1steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-Coll1steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-2.5 mm',key='-Coll1steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='120. mm',key='-Coll1steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-Coll1steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll1steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll1steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll2steel_layer = sg.Frame("Collimator Steel 2",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll2steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Steel',key='-Coll2steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-Coll2steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='270. deg',key='-Coll2steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-Coll2steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll2steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-Coll2steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-2.5 mm',key='-Coll2steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='120. mm',key='-Coll2steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-Coll2steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll2steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll2steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll3steel_layer = sg.Frame("Collimator Steel 3",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll3steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Steel',key='-Coll3steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-Coll3steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='180. deg',key='-Coll3steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-Coll3steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-Coll3steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll3steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-2.5 mm',key='-Coll3steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='120. mm',key='-Coll3steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-Coll3steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll3steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll3steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll4steel_layer = sg.Frame("Collimator Steel 4",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-Coll4steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Steel',key='-Coll4steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-Coll4steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-Coll4steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-Coll4steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-Coll4steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-Coll4steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-2.5 mm',key='-Coll4steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='120. mm',key='-Coll4steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-Coll4steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll4steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-Coll4steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])


# SteelFil_layer = sg.Frame("Steel Filter",
#               [
#                  [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='TsBox',key='-STEELFILTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='Steel',key='-STEELFILMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.01',key='-STEELFILHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='10.',key='-STEELFILHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='10.',key='-STEELFILHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
#               ])

# Not sure if this is even used in the code
TITFIL_layer = sg.Frame("Titanium Filter",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-TITFILTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Titanium',key='-TITFILMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-TITFILROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-TITFILROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-TITFILROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-TITFILTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-TITFILTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-TITFILTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.445 mm',key='-TITFILHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-TITFILHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100. mm',key='-TITFILHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

###########################
DemoFlat_layer = sg.Frame("Demo Flat",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-DEMOFLATTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-DEMOFLATMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-DEMOFLATROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-DEMOFLATROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-DEMOFLATROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-DEMOFLATTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-DEMOFLATTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-DEMOFLATTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='75. mm',key='-DEMOFLATHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1.7 mm',key='-DEMOFLATHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1. mm',key='-DEMOFLATHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])
TopSideBox_layer = sg.Frame("Top side box",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-TSBTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-TSBMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-TSBROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-TSBROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-TSBROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-TSBTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='50. mm',key='-TSBTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='13. mm',key='-TSBTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='75. mm',key='-TSBHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='25. mm',key='-TSBHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='14. mm',key='-TSBHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

BottomSideBox_layer = sg.Frame("Bottom side box",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-BSBTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-BSBMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-BSBROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-90. deg',key='-BSBROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-BSBROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-BSBTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-50. mm',key='-BSBTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='13. mm',key='-BSBTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='75. mm',key='-BSBHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='25. mm',key='-BSBHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='14. mm',key='-BSBHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

DemoRTrap_layer = sg.Frame("Demo RTrap",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-DEMORTRAPTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-DEMORTRAPMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-DEMORTRAPROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90. deg',key='-DEMORTRAPROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-DEMORTRAPROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-DEMORTRAPTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-25. mm',key='-DEMORTRAPTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='6.5 mm',key='-DEMORTRAPTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='150. mm',key='-DEMORTRAPLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='50. mm',key='-DEMORTRAPLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='28. mm',key='-DEMORTRAPLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-DEMORTRAPLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])
DemoLTrap_layer = sg.Frame("Demo LTrap",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='G4RTrap',key='-DEMOLTRAPTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-DEMOLTRAPMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='180. deg',key='-DEMOLTRAPROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='270. deg',key='-DEMOLTRAPROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-DEMOLTRAPROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-DEMOLTRAPTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='25. mm',key='-DEMOLTRAPTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='6.5 mm',key='-DEMOLTRAPTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='150. mm',key='-DEMOLTRAPLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='50. mm',key='-DEMOLTRAPLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='28. mm',key='-DEMOLTRAPLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='2. mm',key='-DEMOLTRAPLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Couch_layer = sg.Frame("Couch",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='TsBox',key='-COUCHTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Aluminum',key='-COUCHMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-COUCHTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.0 mm',key='-COUCHTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Ge/couch/HLZ + Ge/CTDI/RMax mm',key='-COUCHTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.75 mm',key='-COUCHHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='1000.0 mm',key='-COUCHHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='260. mm',key='-COUCHHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

BeamGroup_layer = sg.Frame("Beam Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Group',key='-BEAMGRPTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-BEAMGRPTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. mm',key='-BEAMGRPTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='-1000. mm',key='-BEAMGRPTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-BEAMGRPROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-BEAMGRPROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0. deg',key='-BEAMGRPROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                 
                ])

Beam_layer = sg.Frame("Beam",
                [   
                   [sg.Text('EnergySpec',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Continuous',key='-BEAMSPECTY-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('Type',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Beam',key='-BEAMTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Component',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='BeamPosition',key='-BEAMCOMPO-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('Particle',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='gamma',key='-BEAMPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('PosDistro',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Gaussian',key='-BEAMPOSDISTRO-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('CutOffShape',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Rectangle',key='-BEAMPOSHAPE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('CutOffX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='50. mm',key='-BEAMPOSCUTOFFX-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('CutOffY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='50. mm',key='-BEAMPOSCUTTOFFY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('SpreadX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.4246 mm',key='-BEAMPOSSPRDX-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('SpreadY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.4246 mm',key='-BEAMPOSSPRDY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('AngDistro',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Gaussian',key='-BEAMSPOSANGDISTRO-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('AngCutoffX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90. deg',key='-BEAMPOSANGCUTOFFX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('AngCutoffY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90. deg',key='-BEAMPOSANGCUTOFFY-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('AngSpreadX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='28. deg',key='-BEAMPOSANGSPREADX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('AngSpreadY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='28. deg',key='-BEAMPOSANGSPREADY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Time_layer = sg.Frame("Time Feature",
                [   
                   [sg.Text('Seq Time',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='501',key='-TIMESEQ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Verbosity',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0',key='-TIMEVERBO-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Timeline End',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='501.0 s',key='-TIMELINEEND-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Rotate Func',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='Linear deg',key='-TIMEROTFUNC-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Rotate Rate',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='0.4 deg/s',key='-TIMEROTRATE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Rotate Start',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='90.0 deg',key='-TIMEROTSTART-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('ShowHistoryInt',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text='100000',key='-TIMEHISTINT-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                     
                ])

                