# Helper script to set up the GUI elements. Edits to elements should be made here. Another daughter script called defaultvalues.py is used to store all the default parameters. 
import PySimpleGUI as sg
sg.theme('Reddit')
from src.defaultvalues import *

general_layer = sg.Frame('General Settings',
                [ 
                  [sg.Text('G4 Data Directory',size = (17,1),font=('Helvetica', 14), text_color='black'),
                    sg.In(default_text=default_G4_Directory,key='-G4FOLDERNAME-',size=(50,1),font=('Helvetica', 14),enable_events=True),sg.FolderBrowse(button_text= "Browse", font=('Helvetica', 14))],
                  [sg.Text('TOPAS Directory',size =(17,1),font=('Helvetica', 14),text_color='black'),
                    sg.In(default_text=default_TOPAS_Directory,key='-TOPAS-',size=(50,1),font=('Helvetica', 14),enable_events=True),sg.FileBrowse(button_text= "Browse",font=('Helvetica', 14))],
                  [sg.Text('Seed',size =(9,1),font=('Helvetica', 14),text_color='black'),
                    sg.In(default_text=default_Seed,key='-SEED-',size=(10,1),font=('Helvetica', 14),enable_events=True)],
                  [sg.Text('Threads',size = (9,1),font=('Helvetica', 14),text_color='black'),
                    sg.In(default_text=default_Threads,key='-THREAD-',size=(10,1),font=('Helvetica',14),enable_events=True)],
                  [sg.Text('Histories',size = (9,1),font=('Helvetica',14),text_color='black'),
                    sg.In(default_text=default_Histories,key='-HIST-',size=(10,1),font=('Helvetica',14),enable_events=True),
                    sg.Push(),
                    sg.Button(button_text='Reset all parameters to default', key='-RESET-')],
              ])

main_menu_information_layer = sg.Frame('Instructions on the usage of the GUI', 
                             [ 
                               [sg.Text('Select your Topas and G4 data directories. Next, select the function you would like to enable. ')],
                               [sg.Text('   DICOM allows the user to specify a patient DICOM CT image folder to run simulations on')],
                               [sg.Text('   CTDI validation if for running simulations on CTDI phantom')],
                               [sg.Text('In the following pages, type in your desired value with the units. ')],
                               [sg.Text('By default all lengths are in units of mm and all angles are in units of degrees.')],
                             ]) 

runbuttons_layer= sg.Frame('Activate simulation', 
                           [
                             [sg.Checkbox("Graphics toggle", enable_events=True, key='-GRAPHICS-', default= False)],
                             [sg.Button("Run", enable_events=True, key='-RUN-', disabled=False, font=('Helvetica', 14), disabled_button_color='grey')],
                            ], key ='-BUTTONSACTIVATE-', 
                              visible = False)

function_layer = sg.Frame('Choose your function',
                          [
                            [sg.Checkbox('Use DICOM', enable_events=True, key='-DICOMACTIVATECHECK-'),
                             sg.Checkbox('CTDI validation', enable_events=True , key='-USERACTIVATECHECK-')
                             ],
                          ])

dicom_file_layer = sg.pin(sg.Frame("DICOM inputs",
                              [ 
                                [sg.Text('DICOM Directory',size =(17,1),font=('Helvetica', 14),text_color='black'),
                                 sg.In(default_text=default_DICOM_Directory,key='-DICOM-',size=(50,1),font=('Helvetica', 14),enable_events=True),sg.FolderBrowse(font=('Helvetica', 14))
                                ],
                                [sg.Text('Loaded patient ID:',size =(17,1),font=('Helvetica', 14),text_color='black'),
                                 sg.In(default_text = '', key = '-PATID-' ,size =(17,1),font=('Helvetica', 14),text_color='black', background_color='light grey', enable_events=True, readonly= True)],
                                [sg.Text('DICOM RP file',size =(17,1),font=('Helvetica', 14),text_color='black'),
                                 sg.In(default_text=default_DICOM_RP_file,key='-DICOMRP-',size=(50,1),font=('Helvetica', 14),enable_events=True),sg.FileBrowse(file_types= (("DICOM File",'*.dcm'),) ,font=('Helvetica', 14))
                                ],
                                [sg.Button("Run set up imaging dose simulation",enable_events=True, key='-DICOMBAT-',font=('Helvetica', 14),size=(35,1))],
                              ],
                              key ='-DICOMACTIVATE-', 
                              visible = False
                              ) )

dicom_information_layer = sg.Frame('Instructions on the usage of the DICOM adjustments', 
                             [ 
                               [sg.Text('The programme automatically shifts the patient such that the isocentre of the treatment plan is matched to the isocentre of the beam.')],
                               [sg.Text('In the next page, make any adjustments relative to the ioscentre of the treatment plan.')],
                               [sg.Text('Use the other tabs to make edits to other parameters like collimator openings and beam current. ')],
                             ]) 

dicom_patient_layer = sg.Frame('Patient set up adjustments',
                    [
                        [sg.Text('TransX',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_TRANS_X,key='-DICOM_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_TRANS_Y,key='-DICOM_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_TRANS_Z,key='-DICOM_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_ROT_X,key='-DICOM_ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)], 
                        [sg.Text('RotY',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_ROT_Y,key='-DICOM_ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)], 
                        [sg.Text('RotZ',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_ROT_Z,key='-DICOM_ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)], 
                    ])

dicom_protocol_layer = sg.Frame('Imaging protocol',
                      [ [sg.Text('Imaging mode',size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.Combo(['Image Gently', 'Head', 'Short Thorax', 'Spotlight', 'Thorax', 'Pelvis', 'Pelvis Large'],default_value='Image Gently', key='-IMAGEMODE-', readonly=True ,enable_events=True)],
                        [sg.Text('Fan mode selection',size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.In(default_text='Full fan', key='-FAN-',size = (15,1),font=('Helvetica', 12), text_color='black', enable_events=True,  readonly=True )],
                        [sg.Text('Collimate X1', size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.In(default_text= "0 mm", key = '-DICOM_X1-',size = (15,1),font=('Helvetica', 12), text_color='black', enable_events=True, readonly=True)],
                        [sg.Text('Collimate X2', size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.In(default_text= "0 mm", key = '-DICOM_X2-',size = (15,1),font=('Helvetica', 12), text_color='black', enable_events=True, readonly=True)],
                        [sg.Text('Collimate Y1', size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.In(default_text= "0 mm", key = '-DICOM_Y1-',size = (15,1),font=('Helvetica', 12), text_color='black', enable_events=True, readonly=True)],
                        [sg.Text('Collimate Y2', size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.In(default_text= "0 mm", key = '-DICOM_Y2-',size = (15,1),font=('Helvetica', 12), text_color='black', enable_events=True, readonly=True)],
                      ])

dicom_scan_layer = sg.Frame('Set up imaging parameters', 
                      [ [sg.Text('Start angle',size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.In(default_text=default_DICOM_IMAGE_START_ANGLE,key='-DICOM_STARTROT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('Stop angle',size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.In(default_text=default_DICOM_IMAGE_STOP_ANGLE,key='-DICOM_STOPROT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('Direction of rotation',size = (15,1),font=('Helvetica', 12), text_color='black'),
                         sg.Combo(['Clockwise', 'Anticlockwise'], default_value='Clockwise' ,key='-DICOM_DIRECTROT-', readonly=True )],
                        [sg.Text('kVp',size = (15,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_IMAGE_VOLTAGE,key='-DICOM_IMAGEVOLTAGE-',size=(10,1), font=('Helvetica', 12), enable_events=True)], 
                        [sg.Text('Beam current',size = (15,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_BEAM_CURRENT,key='-DICOM_BEAMCURRENT-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                        ])

dicom_planned_layer = sg.Frame('Treatment plan parameters',
                    [
                        [sg.Text('Isocenter X',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text= default_DICOM_ISOCENTER_X, key='-DICOM_ISOX-',size=(10,1), font=('Helvetica', 12), enable_events=True, readonly=True)],
                        [sg.Text('Isocenter Y',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_ISOCENTER_Y, key='-DICOM_ISOY-',size=(10,1), font=('Helvetica', 12), enable_events=True, readonly=True)],
                        [sg.Text('Isocenter Z',size = (10,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_DICOM_ISOCENTER_Z, key='-DICOM_ISOZ-',size=(10,1), font=('Helvetica', 12), enable_events=True, readonly=True)],
                    ])

# dicom_hidden_layer = sg.Frame('Hidden developer parameters',
#                     [
#                         [sg.Text('X correction',size = (10,1),font=('Helvetica', 12), text_color='black'),
#                         sg.In(default_text= '0. mm', key='-DICOM_X_CORRECTION-',size=(10,1), font=('Helvetica', 12), enable_events=True, readonly=True)],
#                         [sg.Text('Y correction',size = (10,1),font=('Helvetica', 12), text_color='black'),
#                         sg.In(default_text= '0. mm', key='-DICOM_Y_CORRECTION-',size=(10,1), font=('Helvetica', 12), enable_events=True, readonly=True)],
#                         [sg.Text('Z correction',size = (10,1),font=('Helvetica', 12), text_color='black'),
#                         sg.In(default_text= '0. mm', key='-DICOM_Z_CORRECTION-',size=(10,1), font=('Helvetica', 12), enable_events=True, readonly=True)],
#                     ], visible=False)

toggle_layer = sg.pin(sg.Frame("Optimisation component toggle",
                [ [
                    sg.Checkbox("ChamberPlugCentre", default= True , enable_events=True, key='-CPCTOG-', expand_x=True),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("ChamberPlugTop", default= True , enable_events=True, key='-CPTTOG-', expand_x=True),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("ChamberPlugBottom", default= True , enable_events=True, key='-CPBTOG-', expand_x=True),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("ChamberPlugLeft", default= True , enable_events=True, key='-CPLTOG-', expand_x=True)
                  ],
                  [
                    sg.Checkbox("ChamberPlugRight", default= True , enable_events=True, key='-CPRTOG-', expand_x=True),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("ChamberPlugDose_dtm", default= True , enable_events=True, key='-DTMTOG-', expand_x=True),
                    sg.VerticalSeparator(),
                    sg.Checkbox("ChamberPlugDose_tle", default= True , enable_events=True, key='-TLETOG-', expand_x=True),
                    sg.VerticalSeparator(),
                    sg.Checkbox("ChamberPlugDose_dtw", default= True , enable_events=True, key='-DTWTOG-', expand_x=True)
                  ],
                  [
                    sg.Checkbox("CollimatorsVertical", default= True , enable_events=True, key='-COLLVERTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("CollimatorsHorizontal", default= True , enable_events=True, key='-COLLHORTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("TitaniumFilter", default= True , enable_events=True, key='-TITFILTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("BowtieFilter", default= True , enable_events=True, key='-BTFILTOG-')
                  ],
                  [
                    sg.Checkbox("Coll1", default= True , enable_events=True, key='-COLL1TOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("Coll2", default= True , enable_events=True, key='-COLL2TOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("Coll3", default= True , enable_events=True, key='-COLL3TOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("Coll4", default= True , enable_events=True, key='-COLL4TOG-')
                  ],
                  [
                    sg.Checkbox("DemoFlat", default= True , enable_events=True, key='-DEMOFLATTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("DemoRTrap", default= True , enable_events=True, key='-DEMORTRAPTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("DemoLTrap", default= True , enable_events=True, key='-DEMOLTRAPTOG-')
                  ],
                  [
                    sg.Checkbox("topsidebox", default= True , enable_events=True, key='-TSBTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("bottomsidebox", default= True , enable_events=True, key='-BSBTOG-'),
                    sg.VerticalSeparator(), 
                    sg.Checkbox("couch", default= True , enable_events=True, key='-COHTOG-')
                  ]
                ]
                , key ='-USERACTIVATE-', visible = False))

CTDI_information_layer = sg.Frame('Instructions on the usage of the CTDI phantom parameters', 
                             [ 
                               [sg.Text('Edit the parameters here to change between 16 cm and 32 cm phantoms.')],
                               [sg.Text('Simulation will automatically run 5 CTDI simulations for all 5 possible detector position.')],
                               [sg.Text('Use the other tabs to make edits to other parameters like collimator openings and beam current. ')],
                             ]) 

CTDI_layer = sg.Frame('CTDI phantom',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_PHANTOM_RMIN,key='-CTDI_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_PHANTOM_RMAX,key='-CTDI_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_PHANTOM_HL,key='-CTDI_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_PHANTOM_SPHI,key='-CTDI_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_PHANTOM_DPHI,key='-CTDI_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_PHANTOM_TRANS_X,key='-CTDI_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_PHANTOM_TRANS_Y,key='-CTDI_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_PHANTOM_TRANS_Z,key='-CTDI_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_PHANTOM_ROT_X,key='-CTDI_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugCentre_layer = sg.Frame('ChamberPlugCentre',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_CENTER_PLUG_RMIN,key='-CPC_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_CENTER_PLUG_RMAX,key='-CPC_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_CENTER_PLUG_HL,key='-CPC_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_CENTER_PLUG_SPHI ,key='-CPC_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_CENTER_PLUG_DPHI,key='-CPC_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_CENTER_PLUG_TRANS_X,key='-CPC_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_CENTER_PLUG_TRANS_Y,key='-CPC_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_CENTER_PLUG_TRANS_Z,key='-CPC_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_CENTER_PLUG_ROT_X, key='-CPC_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugTop_layer = sg.Frame('ChamberPlugTop',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_TOP_PLUG_RMIN,key='-CPT_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_TOP_PLUG_RMAX,key='-CPT_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_TOP_PLUG_HL,key='-CPT_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_TOP_PLUG_SPHI,key='-CPT_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_TOP_PLUG_DPHI,key='-CPT_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_TOP_PLUG_TRANS_X,key='-CPT_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_TOP_PLUG_TRANS_Y,key='-CPT_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_TOP_PLUG_TRANS_Z,key='-CPT_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_TOP_PLUG_ROT_X,key='-CPT_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugBottom_layer = sg.Frame('ChamberPlugBottom',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_BOTTOM_PLUG_RMIN,key='-CPB_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_BOTTOM_PLUG_RMAX,key='-CPB_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_BOTTOM_PLUG_HL,key='-CPB_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_BOTTOM_PLUG_SPHI,key='-CPB_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_BOTTOM_PLUG_DPHI,key='-CPB_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_BOTTOM_PLUG_TRANS_X,key='-CPB_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_BOTTOM_PLUG_TRANS_Y,key='-CPB_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_BOTTOM_PLUG_TRANS_Z,key='-CPB_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_BOTTOM_PLUG_ROT_X,key='-CPB_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugLeft_layer = sg.Frame('ChamberPlugLeft',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_LEFT_PLUG_RMIN,key='-CPL_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_LEFT_PLUG_RMAX,key='-CPL_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_LEFT_PLUG_HL,key='-CPL_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_LEFT_PLUG_SPHI,key='-CPL_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_LEFT_PLUG_DPHI,key='-CPL_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_LEFT_PLUG_TRANS_X,key='-CPL_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_LEFT_PLUG_TRANS_Y,key='-CPL_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_LEFT_PLUG_TRANS_Z,key='-CPL_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_LEFT_PLUG_ROT_X,key='-CPL_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                    ])

ChamberPlugRight_layer = sg.Frame('ChamberPlugRight',
                    [
                      [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('TsCylinder',size=(10,1), font=('Helvetica', 12))],
                      [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.Text('PMMA',size=(10,1), font=('Helvetica', 12))],
                        [sg.Text('RMin',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_RIGHT_PLUG_RMIN,key='-CPR_RMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RMax',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_RIGHT_PLUG_RMAX,key='-CPR_RMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('HL',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_RIGHT_PLUG_HL,key='-CPR_HL-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('SPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_RIGHT_PLUG_SPHI,key='-CPR_SPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('DPHI',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_RIGHT_PLUG_DPHI,key='-CPR_DPHI-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_RIGHT_PLUG_TRANS_X,key='-CPR_TX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_RIGHT_PLUG_TRANS_Y,key='-CPR_TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_RIGHT_PLUG_TRANS_Z,key='-CPR_TZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                        [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                        sg.In(default_text=default_CTDI_RIGHT_PLUG_ROT_X,key='-CPR_RX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],

                    ])

Scoring_layer = sg.Frame("Scoring",
                [
                   [sg.Text('DTM_Zbins',size = (10,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_DTM_Zbins,key='-DTMZB-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TLE_Zbins',size = (10,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TLE_Zbins,key='-TLEZB-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                  #  [sg.Text('DTW_Zbins',size = (10,1),font=('Helvetica', 12), text_color='black'),
                  #    sg.In(default_text='100',key='-DTWZB-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Physics_layer = sg.Frame("Physics",
                [
                   [sg.Text('List',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_PHYSICS_LIST,key='-PHYLST-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Process',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_PHYSICS_PROCESS,key='-PHYPRO-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Default Type',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_PHYSICS_TYPE,key='-PHYDEFTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Default Modules',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_PHYSICS_MODULES,key='-PHYDEFMO-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('EMRangeMin',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_PHYSICS_EM_MIN,key='-PHYEMIN-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('EMRangeMax',size = (15,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_PHYSICS_EM_MAX,key='-PHYEMAX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

RotationGroup_layer = sg.Frame("Rotation Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_ROTATION_TYPE,key='-ROTTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_ROTATION_ROT_X,key='-ROTROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_ROTATION_ROT_Y,key='-ROTROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_ROTATION_ROT_Z,key='-ROTROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_ROTATION_TRANS_X,key='-ROTTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_ROTATION_TRANS_Y,key='-ROTTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_ROTATION_TRANS_Z,key='-ROTTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

CollimatorVerticalGroup_layer = sg.Frame("Collimators Vertical Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLVERT_TYPE,key='-COLLVERTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLVERT_ROT_X,key='-COLLVERROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLVERT_ROT_Y,key='-COLLVERROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLVERT_ROT_Z,key='-COLLVERROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLVERT_TRANS_Z,key='-COLLVERTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

CollimatorHorizontalGroup_layer = sg.Frame("Collimators Horizontal Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLHOR_TYPE,key='-COLLHORTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLHOR_ROT_X,key='-COLLHORROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLHOR_ROT_Y,key='-COLLHORROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLHOR_ROT_Z,key='-COLLHORROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLLHOR_TRANS_Z,key='-COLLHORTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

# SteelGroup_layer = sg.Frame("Steel Filter Group",
#               [
#                  [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='Group',key='-STEELTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0. deg',key='-STEELROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0. deg',key='-STEELROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0. deg',key='-STEELROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='1.59 mm',key='-STEELTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#               ])

TitaniumGroup_layer = sg.Frame("Titanium Filter Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_TYPE,key='-TITTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_ROT_X,key='-TITROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_ROT_Y,key='-TITROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_ROT_Z,key='-TITROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_TRANS_Z,key='-TITTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Bowtie_layer = sg.Frame("Bowtie Filter Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOW_TYPE,key='-BFTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOW_ROT_X,key='-BFROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOW_ROT_Y,key='-BFROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOW_ROT_Z,key='-BFROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOW_TRANS_X,key='-BFTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOW_TRANS_Y,key='-BFTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOW_TRANS_Z,key='-BFTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Coll1_layer = sg.Frame("Collimator 1",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_TYPE,key='-Coll1TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_MATERIAL,key='-Coll1MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_ROT_X,key='-Coll1ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_ROT_Y,key='-Coll1ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_ROT_Z,key='-Coll1ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_TRANS_X,key='-Coll1TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_TRANS_Y,key='-Coll1TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_TRANS_Z,key='-Coll1TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_LZ,key='-Coll1LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_LY,key='-Coll1LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_LX,key='-Coll1LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_LTX,key='-Coll1LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll2_layer = sg.Frame("Collimator 2",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_TYPE,key='-Coll2TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_MATERIAL,key='-Coll2MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_ROT_X,key='-Coll2ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_ROT_Y,key='-Coll2ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_ROT_Z,key='-Coll2ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_TRANS_X,key='-Coll2TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_TRANS_Y,key='-Coll2TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_TRANS_Z,key='-Coll2TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_LZ,key='-Coll2LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_LY,key='-Coll2LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_LX,key='-Coll2LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_LTX,key='-Coll2LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])
	
Coll3_layer = sg.Frame("Collimator 3",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_TYPE,key='-Coll3TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_MATERIAL,key='-Coll3MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_ROT_X,key='-Coll3ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_ROT_Y,key='-Coll3ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_ROT_Z,key='-Coll3ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_TRANS_X,key='-Coll3TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_TRANS_Y,key='-Coll3TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_TRANS_Z,key='-Coll3TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_LZ,key='-Coll3LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_LY,key='-Coll3LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_LX,key='-Coll3LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_LTX,key='-Coll3LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll4_layer = sg.Frame("Collimator 4",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_TYPE,key='-Coll4TY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_MATERIAL,key='-Coll4MAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_ROT_X,key='-Coll4ROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_ROT_Y,key='-Coll4ROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_ROT_Z,key='-Coll4ROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_TRANS_X,key='-Coll4TRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_TRANS_Y,key='-Coll4TRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_TRANS_Z,key='-Coll4TRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_LZ,key='-Coll4LZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_LY,key='-Coll4LY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_LX,key='-Coll4LX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_LTX,key='-Coll4LTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll1steel_layer = sg.Frame("Collimator Steel 1",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_TYPE,key='-Coll1steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_MATERIAL,key='-Coll1steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_ROT_X,key='-Coll1steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_ROT_Y,key='-Coll1steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_ROT_Z,key='-Coll1steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_TRANS_X,key='-Coll1steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_TRANS_Y,key='-Coll1steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_TRANS_Z,key='-Coll1steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_LZ,key='-Coll1steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_LY,key='-Coll1steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_LX,key='-Coll1steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL1_STEEL_LTX,key='-Coll1steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll2steel_layer = sg.Frame("Collimator Steel 2",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_TYPE,key='-Coll2steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_MATERIAL,key='-Coll2steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_ROT_X,key='-Coll2steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_ROT_Y,key='-Coll2steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_ROT_Z,key='-Coll2steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_TRANS_X,key='-Coll2steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_TRANS_Y,key='-Coll2steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_TRANS_Z,key='-Coll2steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_LZ,key='-Coll2steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_LY,key='-Coll2steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_LX,key='-Coll2steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL2_STEEL_LTX,key='-Coll2steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll3steel_layer = sg.Frame("Collimator Steel 3",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_TYPE,key='-Coll3steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_MATERIAL,key='-Coll3steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_ROT_X,key='-Coll3steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_ROT_Y,key='-Coll3steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_ROT_Z,key='-Coll3steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_TRANS_X,key='-Coll3steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_TRANS_Y,key='-Coll3steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_TRANS_Z,key='-Coll3steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_LZ,key='-Coll3steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_LY,key='-Coll3steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_LX,key='-Coll3steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL3_STEEL_LTX,key='-Coll3steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Coll4steel_layer = sg.Frame("Collimator Steel 4",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_TYPE,key='-Coll4steelTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_MATERIAL,key='-Coll4steelMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_ROT_X,key='-Coll4steelROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_ROT_Y,key='-Coll4steelROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_ROT_Z,key='-Coll4steelROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_TRANS_X,key='-Coll4steelTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_TRANS_Y,key='-Coll4steelTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_TRANS_Z,key='-Coll4steelTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_LZ,key='-Coll4steelLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_LY,key='-Coll4steelLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_LX,key='-Coll4steelLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COLL4_STEEL_LTX,key='-Coll4steelLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])


# SteelFil_layer = sg.Frame("Steel Filter",
#               [
#                  [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='TsBox',key='-STEELFILTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='Steel',key='-STEELFILMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.',key='-STEELFILTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='0.01',key='-STEELFILHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='10.',key='-STEELFILHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
#                  [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
#                    sg.In(default_text='10.',key='-STEELFILHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
#               ])

# Not sure if this is even used in the code
TITFIL_layer = sg.Frame("Titanium Filter",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_TYPE,key='-TITFILTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_MATERIAL,key='-TITFILMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_ROT_X,key='-TITFILROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_ROT_Y,key='-TITFILROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_ROT_Z,key='-TITFILROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_TRANS_X,key='-TITFILTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_TRANS_Y,key='-TITFILTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_TRANS_Z,key='-TITFILTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_HLZ,key='-TITFILHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_HLY,key='-TITFILHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIT_FILTER_HLX,key='-TITFILHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

###########################
DemoFlat_layer = sg.Frame("Demo Flat",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_TYPE,key='-DEMOFLATTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_MATERIAL,key='-DEMOFLATMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_ROT_X,key='-DEMOFLATROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_ROT_Y,key='-DEMOFLATROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_ROT_Z,key='-DEMOFLATROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_TRANS_X,key='-DEMOFLATTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_TRANS_Y,key='-DEMOFLATTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_TRANS_Z,key='-DEMOFLATTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_HLZ,key='-DEMOFLATHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_HLY,key='-DEMOFLATHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_FLAT_HLX,key='-DEMOFLATHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])
TopSideBox_layer = sg.Frame("Top side box",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_TYPE,key='-TSBTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_MATERIAL,key='-TSBMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_ROT_X,key='-TSBROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_ROT_Y,key='-TSBROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_ROT_Z,key='-TSBROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_TRANS_X,key='-TSBTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_TRANS_Y,key='-TSBTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_TRANS_Z,key='-TSBTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_HLZ,key='-TSBHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_HLY,key='-TSBHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TOP_BOX_HLX,key='-TSBHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

BottomSideBox_layer = sg.Frame("Bottom side box",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_TYPE,key='-BSBTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_MATERIAL,key='-BSBMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_ROT_X,key='-BSBROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_ROT_Y,key='-BSBROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_ROT_Z,key='-BSBROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_TRANS_X,key='-BSBTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_TRANS_Y,key='-BSBTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_TRANS_Z,key='-BSBTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_HLZ,key='-BSBHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_HLY,key='-BSBHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BOTTOM_BOX_HLX,key='-BSBHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

DemoRTrap_layer = sg.Frame("Demo RTrap",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_TYPE,key='-DEMORTRAPTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_MATERIAL,key='-DEMORTRAPMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_ROT_X,key='-DEMORTRAPROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_ROT_Y,key='-DEMORTRAPROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_ROT_Z,key='-DEMORTRAPROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_TRANS_X,key='-DEMORTRAPTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_TRANS_Y,key='-DEMORTRAPTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_TRANS_Z,key='-DEMORTRAPTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_LZ,key='-DEMORTRAPLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_LY,key='-DEMORTRAPLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_LX,key='-DEMORTRAPLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_RIGHT_TRAP_LTX,key='-DEMORTRAPLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])
DemoLTrap_layer = sg.Frame("Demo LTrap",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_TYPE,key='-DEMOLTRAPTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_MATERIAL,key='-DEMOLTRAPMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_ROT_X,key='-DEMOLTRAPROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_ROT_Y,key='-DEMOLTRAPROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_ROT_Z,key='-DEMOLTRAPROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_TRANS_X,key='-DEMOLTRAPTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_TRANS_Y,key='-DEMOLTRAPTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_TRANS_Z,key='-DEMOLTRAPTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_LZ,key='-DEMOLTRAPLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_LY,key='-DEMOLTRAPLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_LX,key='-DEMOLTRAPLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('LTX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_LEFT_TRAP_LTX,key='-DEMOLTRAPLTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                ])

Couch_layer = sg.Frame("Couch",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COUCH_TYPE,key='-COUCHTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Material',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COUCH_MATERIAL,key='-COUCHMAT-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COUCH_TRANS_X,key='-COUCHTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COUCH_TRANS_Y,key='-COUCHTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COUCH_TRANS_Z,key='-COUCHTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COUCH_HLZ,key='-COUCHHLZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COUCH_HLY,key='-COUCHHLY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('HLX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_COUCH_HLX,key='-COUCHHLX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   
                ])

BeamGroup_layer = sg.Frame("Beam Group",
                [
                   [sg.Text('Type',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_GROUP_TYPE,key='-BEAMGRPTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_GROUP_TRANS_X,key='-BEAMGRPTRANSX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_GROUP_TRANS_Y,key='-BEAMGRPTRANSY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('TransZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_GROUP_TRANS_Z,key='-BEAMGRPTRANSZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotX',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_GROUP_ROT_X,key='-BEAMGRPROTX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotY',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_GROUP_ROT_Y,key='-BEAMGRPROTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('RotZ',size = (8,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_GROUP_ROT_Z,key='-BEAMGRPROTZ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                 
                ])

Beam_layer = sg.Frame("Beam",
                [   
                   [sg.Text('EnergySpec',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_ENERGYSPEC,key='-BEAMSPECTY-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('Type',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_TYPE,key='-BEAMTY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Component',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_COMPONENT,key='-BEAMCOMPO-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('Particle',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_PARTICLE,key='-BEAMPAR-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('PosDistro',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_POS_DISTRO,key='-BEAMPOSDISTRO-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('CutOffShape',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_CUTOFF_SHAPE,key='-BEAMPOSHAPE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('CutOffX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_CUTOFF_X,key='-BEAMPOSCUTOFFX-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('CutOffY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_CUTOFF_Y,key='-BEAMPOSCUTTOFFY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('SpreadX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_SPREAD_X,key='-BEAMPOSSPRDX-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('SpreadY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_SPREAD_Y,key='-BEAMPOSSPRDY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('AngDistro',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_ANG_DISTRO,key='-BEAMSPOSANGDISTRO-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('AngCutoffX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_ANG_CUTOFF_X,key='-BEAMPOSANGCUTOFFX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('AngCutoffY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_ANG_CUTOFF_Y,key='-BEAMPOSANGCUTOFFY-',size=(10,1), font=('Helvetica', 12), enable_events=True),
                    sg.Text('AngSpreadX',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_ANG_SPREAD_X,key='-BEAMPOSANGSPREADX-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('AngSpreadY',size = (11,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_BEAM_PARAMS_ANG_SPREAD_Y,key='-BEAMPOSANGSPREADY-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                ])

Time_layer = sg.Frame("Time Feature",
                [   
                   [sg.Text('Seq Time',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIME_SEQ_TIME,key='-TIMESEQ-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Verbosity',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIME_VERBOSITY,key='-TIMEVERBO-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Timeline End',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIME_TIME_END,key='-TIMELINEEND-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Rotate Func',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIME_ROT_FUNC,key='-TIMEROTFUNC-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Rotate Rate',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIME_ROT_RATE,key='-TIMEROTRATE-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('Rotate Start',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIME_ROT_START,key='-TIMEROTSTART-',size=(10,1), font=('Helvetica', 12), enable_events=True)],
                   [sg.Text('ShowHistoryInt',size = (14,1),font=('Helvetica', 12), text_color='black'),
                     sg.In(default_text=default_TIME_ROT_HISTORY,key='-TIMEHISTINT-',size=(10,1), font=('Helvetica', 12), enable_events=True)]
                     
                ])

                